"""
Functionality for checking
- score titles (extracted from the source "*.mscz" files) against ...
- the catalogue for which the external source is that kindly curated by the Wikipedia community:
https://en.wikipedia.org/wiki/List_of_chorale_harmonisations_by_Johann_Sebastian_Bach#Numbering_conventions

Uses a modified form of the Levenshtein distance (see code / docs below).

Also, for good measure, check those of
the corresponding analyses (Riemenschneider numbering)
stored in the "When in Rome" meta corpus:
https://github.com/MarkGotham/When-in-Rome/

"""
from typing import List

catalogue = [
    # Chorale text / title", "Zahn", "BWV", "Richter/Kalmus", "CPE", "Riemenschneider"],
    ["Aus meines Herzens Grunde", "5269", "269", "30", "1", "1"],
    ["Ich dank dir, lieber Herre", "5354b", "347", "176", "2", "2"],
    ["Schau, lieber Gott, wie meine Feind (v. 1)", "4431", "153/1", "5", "3", "3"],
    ["Es ist das Heil uns kommen her (v. 11)", "4430", "86/6", "86", "4", "4"],
    ["An Wasserflüssen Babylon", "7663", "267", "23", "5", "5"],
    ["Christus, der ist mein Leben", "132", "281", "46", "7", "6"],
    ["Nun lob, mein Seel, den Herren (v. 3)", "8244", "45124", "271", "6", "7"],
    ["Freuet euch, ihr Christen alle (v. 4)", "7880a", "40/8", "105", "8", "8"],
    ["Ermuntre dich, mein schwacher Geist (v. 9)", "5741", "248/12", "80", "9", "9"],
    ["Aus tiefer Not schrei ich zu dir (v. 5)", "4437", "38/6", "31", "10", "10"],
    ["Jesu, nun sei gepreiset (v. 3)", "8477a", "41/6", "", "11", "11"],
    ["Ein Kind geborn zu Bethlehem (v. 4)", "192b", "65/2", "302", "12", "12"],
    ["Allein zu dir, Herr Jesu Christ (v. 4)", "7292b", "33/6", "16", "13", "13"],
    ["O Herre Gott, dein göttlich Wort (v. 8)", "5690", "184/5", "283", "14", "14"],
    ["Christ lag in Todesbanden", "7012a", "277", "38", "15", "15"],
    ["Es woll uns Gott genädig sein", "7247", "311", "95", "16", "16"],
    ["Erschienen ist der herrlich Tag (v. 4)", "1743", "145/5", "84", "17", "17"],
    ["Gottes Sohn ist kommen", "3294", "318", "115", "18", "18"],
    ["Ich hab mein Sach Gott heimgestellt", "1679", "351", "182", "19", "19"],
    ["Ein feste Burg ist unser Gott", "7377", "302", "74", "20", "20"],
    ["Befiehl du deine Wege (v. 5)", "5385a", "153/5", "160", "21", "21"],
    ["Schmücke dich, o liebe Seele (v. 9)", "6923", "180/7", "304", "22", "22"],
    ["Helft mir Gotts Güte preisen (v. 6)", "5267", "45105", "124", "23", "23"],
    ["Valet will ich dir geben", "5404a", "415", "314", "24", "24"],
    ["Wo soll ich fliehen hin", "2164", "148/6", "29", "25", "25"],
    ["O Ewigkeit, du Donnerwort (vv. 11,16)", "5820", "20/7,/11", "276", "26", "26"],
    ["Es spricht der Unweisen Mund wohl", "4436", "308", "92", "27", "27"],
    ["Nun komm, der Heiden Heiland (v. 8)", "1174", "36/8", "264", "28", "28"],
    ["Weg, mein Herz, mit den Gedanken (v. 12)", "6543", "32/6", "102", "29", "29"],
    ["Jesus Christus, unser Heiland, der von uns ...", "1576", "363", "206", "30", "30"],
    ["Ach lieben Christen, seid getrost", "4441a", "256", "385", "31", "31"],
    ["Nun danket alle Gott", "5142", "386", "257", "32", "32"],
    ["Herr, ich habe mißgehandelt", "3695", "330", "137", "35", "33"],
    ["Erbarm dich mein, o Herre Gott", "5851", "305", "78", "33", "34"],
    ["Ihr Gestirn, ihr hohlen Lüfte (v. 9)", "3614", "248/53", "114", "34", "35"],
    ["Nun bitten wir den Heiligen Geist", "2029", "385", "254", "36", "36"],
    ["Jesu, der du meine Seele", "6804", "352", "185", "37", "37"],
    ["Mache dich, mein Geist, bereit (v. 10)", "6274a", "115/6", "312", "38", "38"],
    ["Ach, was soll ich Sünder machen", "3573b", "259", "10", "39", "39"],
    ["Ach Gott und Herr", "2051", "255", "3", "40", "40"],
    ["Ich hab in Gottes Herz und Sinn (v. 10)", "7568", "65/7", "346", "41", "41"],
    ["Du Friedefürst, Herr Jesu Christ (v. 1)", "4373", "67/7", "68", "42", "42"],
    ["Liebster Gott, wenn werd ich sterben (v. 5)", "6634", "45085", "227", "43", "43"],
    ["Machs mit mir, Gott, nach deiner Güt", "2383", "377", "237", "44", "44"],
    ["Gott Vater, sende deinen Geist (v. 10)", "2496c", "108/6", "224", "46", "45"],
    ["Vom Himmel hoch, da komm ich her (v. 13)", "346", "248/9", "", "45", "46"],
    ["Vater unser im Himmelreich (v. 4)", "2561", "245/5", "317", "47", "47"],
    ["Vater unser im Himmelreich", "2561", "416", "316", "47", "47"],
    ["Ach wie flüchtig, ach wie nichtig (v. 8)", "1887", "45103", "11", "48", "48"],
    ["Mit Fried und Freud ich fahr dahin", "3986", "382", "249", "49", "49"],
    ["O Welt, sieh hier dein Leben (v. 3)", "2293b", "244/37", "292", "50", "50"],
    ["Gelobet seist du, Jesu Christ (v. 7)", "1947", "91/6", "109", "53", "51"],
    ["Wenn mein Stündlein vorhanden ist", "4482ab", "429", "354", "51", "52"],
    ["Das neugeborne Kindelein (v. 4)", "491", "122/6", "57", "52", "53"],
    ["Lobt Gott, ihr Christen, allzugleich (v. 8)", "198", "151/5", "235", "54", "54"],
    ["Wir Christenleut habn jetzund Freud (v. 5)", "2072", "110/7", "380", "57", "55"],
    ["Christum wir sollen loben schon (v. 8)", "297", "121/6", "42", "55", "56"],
    ["O Traurigkeit, o Herzeleid", "1915", "404", "288", "60", "57"],
    ["Herzlich lieb hab ich dich, o Herr (v. 1)", "8326", "174/5", "153", "56", "58"],
    ["Herzliebster Jesu (v. 7)", "983", "245/3", "168", "58", "59"],
    ["Ich freue mich in dir (v. 4)", "5187", "133/6", "181", "61", "60"],
    ["Jesu Leiden, Pein und Tod (v. 33)", "6288b", "159/5", "194", "59", "61"],
    ["Wer nur den lieben Gott läßt walten (v. 7)", "2778", "197/10", "370", "66", "62"],
    ["O Welt, sieh hier dein Leben (vv. 3–4)", "2293b", "245/11", "293", "62", "63"],
    ["Treuer Gott, ich muss dir klagen (v. 6)", "6543", "194/6", "100", "63", "64"],
    ["Was Gott tut, das ist wohlgetan (v. 1)", "5629", "144/3", "338", "64", "65"],
    ["Christ unser Herr zum Jordan kam", "7246", "280", "43", "65", "66"],
    ["Kommt, laßt euch den Herren lehren (v. 6)", "6543", "39/7", "104", "67", "67"],
    ["Wenn wir in höchsten Nöten sein", "394", "431", "358", "68", "68"],
    ["Komm, Heiliger Geist, Herre Gott (v. 3)", "7445a", "226/2", "221", "69", "69"],
    ["Gott sei gelobet und gebenedeiet", "8078", "322", "119", "70", "70"],
    ["Ich ruf zu dir, Herr Jesu Christ (v. 5)", "7400", "177/5", "183", "71", "71"],
    ["Erhalt uns, Herr, bei deinem Wort (v. 2)", "350", "45083", "79", "72", "72"],
    ["Herr Jesu Christ, du höchstes Gut", "4486", "334", "141", "73", "73"],
    ["O Haupt voll Blut und Wunden (vv. 1–2)", "5385a", "244/54", "162", "74", "74"],
    ["Das walt mein Gott", "4217", "291", "59", "75", "75"],
    ["Tröstet, tröstet meine Lieben (v. 3)", "6543", "45107", "103", "76", "76"],
    ["Nun, liebe Seel, nun ist es Zeit (v. 5)", "2461", "248/46", "214", "77", "77"],
    ["Herzliebster Jesu (v. 1)", "983", "244/3", "166", "78", "78"],
    ["Heut triumphieret Gottes Sohn", "2585", "342", "171", "79", "79"],
    ["Befiehl du deine Wege (v. 1)", "5385a", "244/44", "159", "87", "80"],
    ["Christus, der uns selig macht (v. 1)", "6283b", "245/15", "49", "80", "81"],
    ["O großer Gott von Macht (v. 9)", "5101a", "46/6", "", "81", "82"],
    ["Jesu Leiden, Pein und Tod (v. 10)", "6288b", "245/14", "192", "82", "83"],
    ["Nun bitten wir den Heiligen Geist (v. 3)", "2029", "197/5", "255", "83", "84"],
    ["O Gott, du frommer Gott (v. 2)", "5206b", "45/7", "278", "84", "85"],
    ["Wie schön leuchtet der Morgenstern (v. 6)", "8359", "36/4", "377", "85", "86"],
    ["Du, o schönes Weltgebäude (v. 6)", "6773", "56/5", "72", "86", "87"],
    ["Helft mir Gotts Güte preisen (v. 6)", "5267", "45105", "124", "88", "88"],
    ["O Haupt voll Blut und Wunden (v. 9)", "5385a", "244/62", "164", "89", "89"],
    ["Hast du denn, Jesu, dein Angesicht (v. 6)", "1912a", "57/8", "231", "90", "90"],
    ["Verleih uns Frieden gnädlich (complete)", "1945", "42/7", "322", "91", "91"],
    ["Herr Jesu Christ, du höchstes Gut (v. 8)", "4486", "168/6", "143", "92", "92"],
    ["Wach auf, mein Herz, und singe (vv. 9–10)", "159", "194/12", "268", "93", "93"],
    ["Warum betrübst du dich, mein Herz (v. 11)", "1689", "47/5", "333", "94", "94"],
    ["Werde munter, mein Gemüte (v. 6)", "6551", "55/5", "362", "95", "95"],
    ["Selig ist die Seele (v. 9)", "8032", "87/7", "201", "96", "96"],
    ["Nun bitten wir den Heiligen Geist (v. 3)", "2029", "169/7", "256", "97", "97"],
    ["O Haupt voll Blut und Wunden (v. 5)", "5385a", "244/15", "163", "98", "98"],
    ["O Haupt voll Blut und Wunden (v. 6)", "5385a", "244/17", "163", "98", "98"],
    ["Helft mir Gotts Güte preisen (v. 5)", "5267", "45093", "125", "99", "99"],
    ["Durch Adams Fall ist ganz verderbt [de] (v. 8)", "7549", "45064", "73", "100", "100"],
    ["Herr Christ, der einge Gottessohn (v. 5)", "4297a", "164/6", "127", "101", "101"],
    ["Du Lebensfürst, Herr Jesu Christ (vv. 1,13)", "5741", "43/11", "81", "102", "102"],
    ["In allen meinen Taten (v. 15)", "2293b", "45090", "295", "103", "103"],
    ["Wer nur den lieben Gott läßt walten (v. 8)", "2778", "88/7", "368", "104", "104"],
    ["Herzliebster Jesu (v. 4)", "983", "244/46", "167", "105", "105"],
    ["Jesu Leiden, Pein und Tod (v. 20)", "6288b", "245/28", "193", "106", "106"],
    ["Herzlich lieb hab ich dich, o Herr (v. 3)", "8326", "245/40", "154", "107", "107"],
    ["Valet will ich dir geben (v. 3)", "5404a", "245/26", "315", "108", "108"],
    ["Singen wir aus Herzensgrund (v. 4)", "4816", "187/7", "308", "109", "109"],
    ["So wahr ich lebe, spricht dein Gott (v. 6)", "2561", "102/7", "320", "110", "110"],
    ["Herzliebster Jesu (vv. 8–9)", "983", "245/17", "169", "111", "111"],
    ["Wer weiß, wie nahe mir mein Ende (v. 12)", "2778", "84/5", "373", "112", "112"],
    ["Christus, der uns selig macht (v. 8)", "6283b", "245/37", "50", "113", "113"],
    ["Von Gott will ich nicht lassen", "5264b", "419", "326", "114", "114"],
    ["Was mein Gott will, das g'scheh allzeit (v. 1)", "7568", "244/25", "342", "115", "115"],
    ["Nun lob, mein Seel, den Herren (v. 5)", "8244", "45167", "272", "116", "116"],
    ["O Welt, sieh hier dein Leben (v. 5)", "2293b", "244/10", "294", "117", "117"],
    ["In dich hab ich gehoffet, Herr (v. 5)", "2461", "244/32", "213", "118", "118"],
    ["Was alle Weisheit in der Welt (v. 8)", "7246", "176/6", "45", "119", "119"],
    ["Barmherzger Vater, höchster Gott (v. 9)", "7568", "103/6", "348", "120", "120"],
    ["Werde munter, mein Gemüte (v. 6)", "6551", "244/40", "361", "121", "121"],
    ["Ist Gott mein Schild und Helfersmann (v. 4)", "2542", "85/6", "216", "122", "122"],
    ["Zeuch ein zu deinen Toren (v. 5)", "5267", "183/5", "126", "123", "123"],
    ["Auf, auf, mein Herz, und du mein ganzer ...", "824", "268", "24", "124", "124"],
    ["Der Herr ist mein getreuer Hirt (v. 1)", "4457", "104/6", "13", "125", "125"],
    ["Durch Adams Fall ist ganz verderbt [de] (v. 8)", "7549", "45064", "73", "126", "126"],
    ["Dies sind die heilgen zehn Gebot", "1951", "298", "66", "127", "127"],
    ["Alles ist an Gottes Segen", "3842f", "263", "19", "128", "128"],
    ["Keinen hat Gott verlassen", "5395", "369", "217", "129", "129"],
    ["Meine Seele erhebet den Herren", "7372~", "324", "121", "130", "130"],
    ["Liebster Jesu, wir sind hier", "3498b", "373", "228", "131", "131"],
    ["Kyrie, Gott Vater in Ewigkeit", "8600", "371", "225", "132", "132"],
    ["Wir glauben all an einen Gott, Schöpfer ...", "7971", "437", "382", "133", "133"],
    ["Du, o schönes Weltgebäude", "6773", "301", "71", "137", "134"],
    ["Gott der Vater wohn uns bei", "8507", "317", "113", "134", "135"],
    ["Herr Jesu Christ, dich zu uns wend", "625", "332", "139", "136", "136"],
    ["Wer Gott vertraut, hat wohl gebaut", "8207b", "433", "366", "135", "137"],
    ["Jesu, meine Freude (v. 5)", "8032", "64/8", "200", "138", "138"],
    ["Fröhlich soll mein Herze springen (v. 15)", "6461", "248/33", "335", "139", "139"],
    ["In allen meinen Taten", "2276", "367", "211", "140", "140"],
    ["Seelenbräutigam", "3255b", "409", "306", "141", "141"],
    ["Schwing dich auf zu deinem Gott (v. 2)", "4870", "40/6", "305", "142", "142"],
    ["In dulci jubilo", "4947", "368", "215", "143", "143"],
    ["Wer in dem Schutz des Höchsten ist", "4438", "339", "151", "144", "144"],
    ["Warum betrübst du dich, mein Herz", "1689", "420", "331", "145", "145"],
    ["Wer nur den lieben Gott läßt walten", "2778", "434", "367", "146", "146"],
    ["Wenn ich in Angst und Not", "4233", "427", "352", "147", "147"],
    ["Uns ist ein Kindlein heut geborn", "493", "414", "313", "148", "148"],
    ["Nicht so traurig, nicht so sehr", "3355", "384", "253", "149", "149"],
    ["Welt, ade! Ich bin dein müde (v. 1)", "6531", "Anh. 170", "350", "150", "150"],
    ["Meinen Jesum laß ich nicht, Jesus ...", "3448a", "379", "241", "151", "151"],
    ["Meinen Jesum laß ich nicht, weil ... (v. 6)", "3449", "154/8", "244", "152", "152"],
    ["Alle Menschen müssen sterben", "6778", "262", "17", "153", "153"],
    ["Der du bist drei in Einigkeit", "335", "293", "61", "154", "154"],
    ["Hilf, Herr Jesu, laß gelingen", "3687a", "344", "173", "155", "155"],
    ["Ach Gott, wie manches Herzeleid (v. 18)", "553a", "45080", "8", "156", "156"],
    ["Wo Gott zum Haus nicht gibt sein Gunst", "305", "438", "389", "157", "157"],
    ["Der Tag, der ist so freudenreich", "7870", "294", "62", "158", "158"],
    ["Als der gütige Gott", "1645", "264", "20", "159", "159"],
    ["Gelobet seist du, Jesu Christ (v. 7)", "1947", "64/2", "108", "160", "160"],
    ["Ihr Gestirn, ihr hohlen Lüfte", "3703", "366", "210", "161", "161"],
    ["Das alte Jahr vergangen ist", "381c", "288", "55", "162", "162"],
    ["Für Freuden laßt uns springen", "2339", "313", "106", "163", "163"],
    ["Herr Gott, dich loben alle wir", "368", "326", "129", "167", "164"],
    ["O Lamm Gottes, unschuldig", "4361a", "401", "285", "165", "165"],
    ["Es stehn vor Gottes Throne", "4298", "309", "93", "166", "166"],
    ["Du großer Schmerzensmann", "5159", "300", "70", "164", "167"],
    ["Heut ist, o Mensch, ein großer Trauertag", "8569(A)", "341", "170", "168", "168"],
    ["Jesu, der du selbsten wohl", "6335", "355", "189", "169", "169"],
    ["Nun komm, der Heiden Heiland (v. 8)", "1174", "62/6", "265", "170", "170"],
    ["Schaut, ihr Sünder", "8569(B)", "408", "303", "171", "171"],
    ["Sei gegrüßet, Jesu gütig", "3889b", "410", "307", "172", "172"],
    ["O Herzensangst, o Bangigkeit", "1003", "400", "284", "173", "173"],
    ["Jesus Christus, unser Heiland, der den Tod ...", "1978", "364", "207", "174", "174"],
    ["Jesus, meine Zuversicht", "3432b", "365", "208", "175", "175"],
    ["Erstanden ist der heilge Christ", "1746", "306", "85", "176", "176"],
    ["Ach bleib bei uns, Herr Jesu Christ", "493", "253", "1", "177", "177"],
    ["Das neugeborne Kindelein (v. 4)", "491", "122/6", "57", "178", "178"],
    ["Wachet auf, ruft uns die Stimme (v. 3)", "8405", "140/7", "329", "179", "179"],
    ["Als Jesus Christus in der Nacht", "258", "265", "21", "180", "180"],
    ["Gott hat das Evangelium", "1788", "319", "116", "181", "181"],
    ["Wär Gott nicht mit uns diese Zeit (v. 3)", "4434", "45060", "330", "182", "182"],
    ["Nun freut euch, lieben Christen g'mein", "4427", "388", "261", "183", "183"],
    ["Christ lag in Todesbanden (v. 7)", "7012a", "45142", "41", "184", "184"],
    ["Nun freut euch, Gottes Kinder all", "364", "387", "260", "185", "185"],
    ["Ach Gott, erhör mein Seufzen", "1831a", "254", "2", "186", "186"],
    ["Komm, Gott Schöpfer, Heiliger Geist", "295", "370", "218", "187", "187"],
    ["Ich dank dir schon durch deinen Sohn", "247b", "349", "179", "188", "188"],
    ["Herr Jesu Christ, wahr Mensch und Gott", "423", "336", "146", "189", "189"],
    ["Herr, nun laß in Friede", "3302", "337", "148", "190", "190"],
    ["Von Gott will ich nicht lassen (v. 9)", "5264b", "73/5", "328", "191", "191"],
    ["Gottlob, es geht nunmehr zu Ende", "2855", "321", "118", "192", "192"],
    ["Was bist du doch, o Seele, so betrübet", "1837", "424", "337", "193", "193"],
    ["Liebster Immanuel, Herzog ... (v. 6)", "4932c", "123/6", "229", "194", "194"],
    ["Wie schön leuchtet der Morgenstern (v. 6)", "8359", "36/4", "377", "195", "195"],
    ["Da der Herr Christ zu Tische saß", "2503", "285", "52", "196", "196"],
    ["Christ ist erstanden", "8584", "276", "36", "197", "197"],
    ["Christus, der uns selig macht", "6283b", "283", "48", "198", "198"],
    ["Hilf, Gott, daß mirs gelinge", "4329", "343", "172", "199", "199"],
    ["Christus ist erstanden, hat überwunden", "6240c", "284", "51", "200", "200"],
    ["O Mensch, bewein dein Sünde groß", "8303", "402", "286", "201", "201"],
    ["O wir armen Sünder", "8187h", "407", "301", "202", "202"],
    ["O Mensch, schau Jesum Christum an", "3994c", "403", "287", "203", "203"],
    ["Wer weiß, wie nahe mir mein Ende (v. 1)", "2778", "166/6", "372", "204", "204"],
    ["Herr Gott, dich loben wir", "8652", "328", "133", "205", "205"],
    ["So gibst du nun, mein Jesu, gute Nacht", "849", "412", "310", "206", "206"],
    ["Des Heilgen Geistes reiche Gnad", "3706", "295", "63", "207", "207"],
    ["Als vierzig Tag nach Ostern warn", "1743", "266", "22", "208", "208"],
    ["Dir, dir, Jehova, will ich singen", "3068", "299", "67", "209", "209"],
    ["Christe, du Beistand deiner Kreuzgemeine", "993", "275", "35", "210", "210"],
    ["Weltlich Ehr und zeitlich Gut", "4975", "426", "351", "211", "211"],
    ["Herr, ich denk an jene Zeit", "4840", "329", "136", "212", "212"],
    ["O wie selig seid ihr doch, ihr Frommen", "1583", "405", "299", "213", "213"],
    ["Mitten wir im Leben sind", "8502", "383", "252", "214", "214"],
    ["Verleih uns Frieden gnädlich (complete)", "1945", "126/6", "321", "215", "215"],
    ["Es ist genug (v. 5)", "7173", "60/5", "91", "216", "216"],
    ["Ach Gott, wie manches Herzeleid (vv. 16–18)", "553a", "153/9", "9", "217", "217"],
    ["Lass, o Herr, dein Ohr sich neigen", "6863", "372", "226", "218", "218"],
    ["O wie selig seid ihr doch, ihr Frommen", "1581", "406", "300", "219", "219"],
    ["Sollt ich meinem Gott nicht singen", "7886b", "413", "311", "220", "220"],
    ["Herr, straf mich nicht in deinem Zorn", "4606a", "338", "149", "221", "221"],
    ["Nun preiset alle Gottes Barmherzigkeit", "4089a", "391", "273", "222", "222"],
    ["Ich dank dir, Gott, für all Wohltat", "8090b", "346", "175", "223", "223"],
    ["Das walt Gott Vater und Gott Sohn", "673", "290", "58", "224", "224"],
    ["Gott, der du selber bist das Licht", "5814", "316", "112", "225", "225"],
    ["Herr Jesu Christ, du hast bereit't", "4711", "333", "140", "226", "226"],
    ["Lobet den Herren, denn er ist sehr ...", "975", "374", "232", "227", "227"],
    ["Danket dem Herrn, denn er ist sehr...", "12", "286", "53", "228", "228"],
    ["Ich danke dir, o Gott, in deinem Throne", "3199", "350", "180", "229", "229"],
    ["Christ, der du bist der helle Tag", "384", "273", "33", "230", "230"],
    ["Die Nacht ist kommen", "5001", "296", "64", "231", "231"],
    ["Die Sonn hat sich mit ihrem Glanz", "923", "297", "65", "232", "232"],
    ["Jesu, meiner Seelen Wonne (v. 2)", "6551", "154/3", "365", "233", "233"],
    ["Gott lebet noch", "7951", "320", "117", "234", "234"],
    ["Heilig, heilig (or)", "", "", "", "", ""],
    ["Sanctus, Sanctus Dominus Deus Sabaoth", "8633", "325", "123", "235", "235"],
    ["O Jesu, du mein Bräutigam", "314", "335", "145", "236", "236"],
    ["Was betrübst du dich, mein Herze", "6830", "423", "336", "237", "237"],
    ["Es wird schier der letzte Tag herkommen", "1423", "310", "94", "238", "238"],
    ["Den Vater dort oben", "4795", "292", "60", "239", "239"],
    ["Nun sich der Tag geendet hat [choralwiki]", "212b", "396", "274", "240", "240"],
    ["Was willst du dich, o meine Seele, kränken", "7844", "425", "349", "241", "241"],
    ["Wie bist du, Seele, in mir so gar betrübt", "4092", "435", "374", "242", "242"],
    ["Jesu, du mein liebstes Leben", "7891", "356", "190", "243", "243"],
    ["Jesu, Jesu, du bist mein", "6446", "357", "191", "244", "244"],
    ["Christe, der du bist Tag und Licht", "343", "274", "34", "245", "245"],
    ["Singt dem Herrn ein neues Lied", "6424", "411", "309", "246", "246"],
    ["Wenn wir in höchsten Nöten sein", "394", "432", "359", "247", "247"],
    ["Sei Lob und Ehr dem höchsten Gut (vv. 4, 9)", "4430", "117/4,/9", "90", "248", "248"],
    ["Allein Gott in der Höh sei Ehr", "4457", "260", "12", "249", "249"],
    ["Ein feste Burg ist unser Gott", "7377", "303", "75", "250", "250"],
    ["Ich bin ja, Herr, in deiner Macht", "5878", "345", "174", "251", "251"],
    ["Jesu, nun sei gepreiset", "8477a", "362", "203", "252", "252"],
    ["Wenn einer alle Ding verstünd (v. 8)?", "4431", "77/6", "6", "253", "253"],
    ["O Gottes Sohn, Herr Jesu Christ (v. 5)?", "4431", "77/6", "6", "253", "253"],
    ["Ach Gott, vom Himmel sieh darein", "4431", "77/6", "6", "253", "253"],
    ["Treuer Gott, ich muss dir klagen (v. 12)", "6543", "45102", "101", "254", "254"],
    ["Was frag ich nach der Welt (v. 1)", "5206b", "64/4", "280", "255", "255"],
    ["Treuer Gott, ich muss dir klagen (v. 6)", "6543", "194/6", "100", "256", "256"],
    ["Wach auf, mein Herz, und singe (vv. 9–10)", "159", "194/12", "268", "257", "257"],
    ["Mein Augen schließ ich jetzt", "1067", "378", "240", "258", "258"],
    ["Verleih uns Frieden gnädlich (complete)", "1945", "42/7", "322", "259", "259"],
    ["Es ist gewißlich an der Zeit", "4429a", "307", "262", "260", "260"],
    ["Christ lag in Todesbanden", "7012a", "279", "40", "261", "261"],
    ["Ach Gott, vom Himmel sieh darein (v. 6)", "4431", "45079", "7", "262", "262"],
    ["Jesu, meine Freude (vv. 1, 6)", "8032", "227/1,/11", "196", "263", "263"],
    ["Jesu, meines Herzens Freud", "4798d", "361", "202", "264", "264"],
    ["Was mein Gott will, das g'scheh allzeit (v. 1)", "7568", "144/6", "343", "265", "265"],
    ["Herr Jesu Christ, ich schrei zu dir (v. 12)", "4486", "48/7", "144", "266", "266"],
    ["Herr Jesu Christ, du höchstes Gut", "4486", "48/7", "144", "266", "266"],
    ["Nimm von uns, Herr, du treuer Gott (v. 7)", "2561", "90/5", "319", "267", "267"],
    ["Nun lob, mein Seel, den Herren", "8244", "389", "269", "268", "268"],
    ["Jesu, der du meine Seele", "6804", "353", "186", "269", "269"],
    ["Herzlich tut mich verlangen (v. 4)", "5385a", "161/6", "161", "270", "270"],
    ["Gib dich zufrieden und sei stille", "7417a", "315", "111", "271", "271"],
    ["Ich dank dir, lieber Herre", "5354b", "348", "177", "272", "272"],
    ["Ein feste Burg ist unser Gott (v. 4)", "7377", "80/8", "76", "273", "273"],
    ["O Ewigkeit, du Donnerwort", "5820", "397", "275", "274", "274"],
    ["O Welt, sieh hier dein Leben", "2293b", "393", "289", "275", "275"],
    ["Lobt Gott, ihr Christen, allzugleich", "198", "375", "233", "276", "276"],
    ["Herzlich lieb hab ich dich, o Herr", "8326", "340", "152", "277", "277"],
    ["Wie schön leuchtet der Morgenstern", "8359", "436", "375", "278", "278"],
    ["Ach Gott und Herr (v. 4)", "2051", "48/3", "4", "279", "279"],
    ["Eins ist not, ach Herr, dies Eine", "7127", "304", "77", "280", "280"],
    ["Wo soll ich fliehen hin (v. 7)", "2164", "89/6", "26", "281", "281"],
    ["Treuer Gott, ich muss dir klagen (v. 12)", "6543", "45102", "101", "282", "282"],
    ["Jesu, meine Freude (v. 4)", "8032", "227/7", "199", "283", "283"],
    ["Wär Gott nicht mit uns diese Zeit", "4441a", "257", "388", "284", "285"],
    ["Befiehl du deine Wege", "5385a", "270", "157", "285", "286"],
    ["Herr, ich habe mißgehandelt", "3695", "331", "138", "286", "287"],
    ["Gelobet seist du, Jesu Christ", "1947", "314", "107", "287", "288"],
    ["Nun ruhen alle Wälder", "2293b", "392", "298", "288", "289"],
    ["Es ist das Heil uns kommen her (vv. 7–8)", "4430", "45116", "87", "289", "290"],
    ["Was frag ich nach der Welt (vv. 7–8)", "5206b", "94/8", "281", "290", "291"],
    ["Nimm von uns, Herr, du treuer Gott (v. 7)", "2561", "101/7", "318", "291", "292"],
    ["Was Gott tut, das ist wohlgetan (v. 6)", "5629", "69a/6", "", "292", "293"],
    ["Herr Jesu Christ, du höchstes Gut (v. 8)", "4486", "113/8", "142", "293", "294"],
    ["Herr Jesu Christ, meins Lebens Licht", "314", "335", "145", "294", "295"],
    ["Nun lob, mein Seel, den Herren", "8244", "390", "270", "295", "296"],
    ["Jesu, der du meine Seele (v. 12)", "6804", "78/7", "188", "296", "297"],
    ["Freu dich sehr, o meine Seele (v. 9)", "6543", "45126", "99", "297", "298"],
    ["Meinen Jesum laß ich nicht, weil ...", "3449", "380", "242", "298", "299"],
    ["Warum betrübst du dich, mein Herz", "1689", "421", "332", "299", "300"],
    ["Ach lieben Christen, seid getrost (v. 6)", "4441a", "114/7", "386", "300", "301"],
    ["Hilf, Gott, daß mirs gelinge", "4329", "343", "172", "301", "302"],
    ["Herr Christ, der einge Gottessohn (v. 5)", "4297a", "96/6", "128", "302", "303"],
    ["Wo soll ich fliehen hin (v. 11)", "2164", "45112", "28", "303", "304"],
    ["Wie schön leuchtet der Morgenstern (v. 6)", "8359", "36/4", "377", "304", "305"],
    ["O Mensch, bewein dein Sünde groß", "8303", "402", "286", "305", "306"],
    ["Christus, der uns selig macht", "6283b", "283", "48", "306", "307"],
    ["Ach Gott, wie manches Herzeleid (v. 18)", "553a", "45080", "8", "307", "308"],
    ["Ein Lämmlein geht und trägt die Schuld", "7663", "267", "23", "308", "309"],
    ["Durch dein Gefängnis, Gottes Sohn (1 v.)", "2383", "245/22", "239", "309", "310"],
    ["Dank sei Gott in der Höhe", "5391", "287", "54", "310", "311"],
    ["O Gott, du frommer Gott", "5206b", "398", "277", "311", "312"],
    ["Der Herr ist mein getreuer Hirt (v. 5)", "4457", "112/5", "14", "312", "313"],
    ["Das alte Jahr vergangen ist", "381c", "289", "56", "313", "314"],
    ["O Gott, du frommer Gott", "5148", "399", "282", "314", "315"],
    ["Christus, der ist mein Leben", "132", "282", "47", "315", "316"],
    ["Herr, wie du willst, so schicks ... [de] (v. 1)", "4438", "156/6", "150", "316", "317"],
    ["Herr, wie du willst, so schick's mit mir [de]", "4438", "339", "151", "317", "318"],
    ["Heilig, heilig (or)", "", "", "", "", ""],
    ["Sanctus, Sanctus Dominus Deus Sabaoth", "8633", "325", "123", "318", "319"],
    ["Gott sei uns gnädig und barmherzig", "7372", "323", "120", "319", "320"],
    ["Wir Christenleut habn jetzund Freud (v. 3)", "2072", "40/3", "379", "320", "321"],
    ["Wenn mein Stündlein vorhanden ist", "4482a,b", "428", "353", "321", "322"],
    ["Wie schön leuchtet der Morgenstern (v. 4)", "8359", "172/6", "376", "322", "323"],
    ["Jesu, meine Freude (v. 2)", "8032", "81/7", "197", "323", "324"],
    ["Mit Fried und Freud ich fahr dahin (v. 4)", "3986", "83/5", "250", "324", "325"],
    ["Der Herr ist mein getreuer Hirt (v. 1)", "4457", "104/6", "13", "325", "326"],
    ["Jesu, nun sei gepreiset (v. 2)", "8477a", "190/7", "205", "326", "327"],
    ["Liebster Jesu, wir sind hier", "3498b", "373", "228", "327", "328"],
    ["Sei Lob und Ehr dem höchsten Gut", "4430", "251", "89", "328", "329"],
    ["Nun danket alle Gott", "5142", "252", "258", "329", "330"],
    ["Wo soll ich fliehen hin (v. 9)", "2164", "136/6", "27", "330", "331"],
    ["Von Gott will ich nicht lassen", "5264b", "418", "325", "331", "332"],
    ["Es woll uns Gott genädig sein (v. 3)", "7247", "69/6", "97", "332", "333"],
    ["Vor deinen Thron tret ich hiermit", "368", "327", "132", "333", "334"],
    ["Es ist das Heil uns kommen her (v. 12)", "4430", "155/5", "88", "334", "335"],
    ["Wo Gott der Herr nicht bei uns hält", "4441a", "258", "383", "335", "336"],
    ["O Gott, du frommer Gott (v. 1)", "5148", "45101", "", "336", "337"],
    ["Auf, mein Herz, des Herren Tag (v. 1)", "3432b", "145/a", "209", "337", "338"],
    ["Ich armer Mensch, ich armer Sünder (v. 1)", "2778", "179/6", "371", "338", "339"],
    ["Befiehl du deine Wege", "5393", "272", "32", "339", "340"],
    ["Ich dank dir, lieber Herre (v. 4)", "5354b", "37/6", "178", "340", "341"],
    ["Lobt Gott, ihr Christen, allzugleich", "198", "376", "234", "341", "342"],
    ["Du Lebensfürst, Herr Jesu Christ (v. 4)", "5741", "45088", "82", "342", "343"],
    ["Wir singen dir, Immanuel (v. 2)", "346", "248/23", "", "343", "344"],
    ["Wie soll ich dich empfangen (v. 1)", "5385a", "248/5", "165", "344", "345"],
    ["Meines Lebens letzte Zeit", "6380", "381", "248", "345", "346"],
    ["Was Gott tut, das ist wohlgetan", "5629", "250", "339", "346", "347"],
    ["Meinen Jesum laß ich nicht, weil ... (v. 5)", "3449", "70/11", "243", "347", "348"],
    ["Barmherzger Vater, höchster Gott (v. 9)", "7568", "103/6", "348", "348", "349"],
    ["Jesu, meiner Seelen Wonne", "6551", "360", "364", "349", "350"],
    ["Wenn mein Stündlein vorhanden ist", "4482a,b", "430", "355", "350", "351"],
    ["Es woll uns Gott genädig sein", "7247", "312", "96", "351", "352"],
    ["Der Herr ist mein getreuer Hirt (v. 5)", "4457", "112/5", "14", "352", "353"],
    ["Sei Lob und Ehr dem höchsten Gut (vv. 4,9)", "4430", "117/4,/9", "90", "353", "354"],
    ["In allen meinen Taten (v. 9)", "2293b", "44/7", "296", "354", "355"],
    ["Jesu, meine Freude", "8032", "358", "195", "355", "356"],
    ["Warum sollt ich mich denn grämen", "6461", "422", "334", "356", "357"],
    ["Meine Seele erhebt den Herren (doxology)", "7372~", "45117", "122", "357", "358"],
    ["Allein zu dir, Herr Jesu Christ", "7292b", "261", "15", "358", "359"],
    ["Lasst Furcht und Pein (v. 4)", "2072", "248/35", "381", "359", "360"],
    ["Ermuntre dich, mein schwacher Geist (v. 9)", "5741", "248/12", "80", "360", "361"],
    ["Ich steh an deiner Krippen hier (v. 1)", "4429a", "248/59", "263", "361", "362"],
    ["O Welt, sieh hier dein Leben", "2293b", "395", "291", "362", "363"],
    ["Von Gott will ich nicht lassen", "5264b", "417", "324", "363", "364"],
    ["Jesu meiner Seelen Wonne", "6551", "359", "363", "364", "365"],
    ["O Welt, sieh hier dein Leben", "2293b", "394", "290", "365", "366"],
    ["Befiehl du deine Wege", "5385a", "271", "158", "366", "367"],
    ["Hilf, Herr Jesu, laß gelingen (v. 5)", "N/1", "248/42", "", "367", "368"],
    ["Jesu, der du meine Seele", "6804", "354", "187", "368", "369"],
    ["Gott Vater, sende deinen Geist (v. 2)", "2496c", "74/8", "223", "369", "370"],
    ["Christ lag in Todesbanden", "7012a", "278", "39", "370", "371"],
    ["Herr Jesu Christ, wahr Mensch und Gott (v. 8)", "2570", "127/5", "147", "283bis", "384"]
]

col_dict = {
    "text": 0,
    "title": 0,
    "name": 0,
    "Zahn": 1,
    "BWV": 2,
    "Kalmus": 3,
    "CPE": 4,
    "Riemenschneider": 5
}

score_titles = [
    None,
    "Aus meines Herzens Grunde",
    "Ich dank' dir, lieber Herre",
    "Ach Gott, vom Himmel sieh' darein",
    "Es ist das Heil uns kommen her",
    "An Wasserflüssen Babylon",
    "Nun lob', mein' Seel', den Herren",
    "Christus, der ist mein Leben",
    "Freuet euch, ihr Christen",
    "Ermuntre dich, mein schwacher Geist",
    "Aus tiefer Not schrei' ich zu dir",
    "Jesu, nun sei gepreiset",
    "Puer natus in Bethlehem",
    "Allein zu dir, Herr Jesu Christ",
    "O Herre Gott, dein göttlich Wort",
    "Christ lag in Todesbanden",
    "Es woll' uns Gott genädig sein",
    "Erschienen ist der herrliche Tag",
    "Gottes Sohn ist kommen",
    "Ich hab' mein' Sach' Gott heimgestellt",
    "Ein' feste Burg ist unser Gott",
    "Herzlich tut mich verlangen",
    "Schmücke dich, o liebe Seele",
    "Zeuch ein zu deinen Toren",
    "Valet will ich dir geben",
    "Wo soll ich fliehen hin",
    "O Ewigkeit, du Donnerwort",
    "Es spricht der Unweisen Mund wohl",
    "Nun komm, der Heiden Heiland",
    "Freu' dich sehr, o meine Seele",
    "Jesus Christus, unser Heiland",
    "Ach lieben Christen, seid getrost",
    "Nun danket alle Gott",
    "Erbarm' dich mein, o Herre Gott",
    "Gott des Himmels und der Erden",
    "Herr, ich habe missgehandelt",
    "Nun bitten wir den heiligen Geist",
    "Jesu, der du meine Seele",
    "Straf' mich nicht in deinem Zorn",
    "Ach, was soll ich Sünder machen",
    "Ach Gott und Herr",
    "Was mein Gott will, das gescheh' allzeit",
    "Du Friedensfürst, Herr Jesu Christ",
    "Liebster Gott, wann werd' ich sterben",
    "Mach's mit mir, Gott, nach deiner Güt'",
    "Vom Himmel hoch da komm' ich her",
    "Kommt her zu mir, spricht Gottes Sohn",
    "Vater unser im Himmelreich",
    "Ach wie nichtig, ach wie flüchtig",
    "Mit Fried' und Freud' fahr' ich dahin",
    "In allen meinen Taten",
    "Wenn mein Stündlein vorhanden ist",
    "Das neugeborne Kindelein",
    "Gelobet seist du Jesu Christ",
    "Lobt Gott, ihr Christen, allzugleich",
    "Christum wir sollen loben schon",
    "Herzlich lieb hab' ich dich, o Herr",
    "Wir Christenleut'",
    "Herzliebster Jesu, was hast du verbrochen",
    "Jesu Leiden, Pein und Tod",
    "O Traurigkeit, o Herzeleid",
    "Ich freue mich in dir",
    "Nun ruhen alle Wälder",
    "Freu' dich sehr, o meine Seele",
    "Was Gott tut, das ist wohlgetan",
    "Christ, unser Herr, zum Jordan kam",
    "Wer nur den lieben Gott lässt walten",
    "Freu' dich sehr, o meine Seele",
    "Wenn wir in höchsten Nöten sein",
    "Komm, heiliger Geist, Herre Gott",
    "Gott sei gelobet und gebenedeiet",
    "Ich ruf' zu dir, Herr Jesu Christ",
    "Erhalt' uns, Herr, bei deinem Wort",
    "Herr Jesu Christ, du höchstes Gut",
    "O Haupt voll Blut und Wunden",
    "Das walt' mein Gott",
    "Freu' dich sehr, o meine Seele",
    "In dich hab' ich gehoffet, Herr",
    "Herzliebster Jesu, was hast du verbrochen",
    "Heut' triumphiret Gottes Sohn",
    "Christus, der uns selig macht",
    "O großer Gott von Macht",
    "Jesu Leiden, Pein und Tod",
    "Nun bitten wir den heiligen Geist",
    "O Gott, du frommer Gott",
    "Wie schön leuchtet der Morgenstern",
    "Du, o schönes Weltgebäude",
    "O Haupt voll Blut und Wunden",
    "Helft mir Gott's Güte preisen",
    "O Haupt voll Blut und Wunden",
    "Hast du denn, Jesu, dein Angesicht",
    "Verleih' uns Frieden gnädiglich",
    "O Jesu Christ, du höchstes Gut",
    "Wach' auf, mein Herz, und singe",
    "Warum betrübst du dich, mein Herz",
    "Werde munter, mein Gemüte",
    "Jesu, meine Freude",
    "Nun bitten wir den heiligen Geist",
    "O Haupt voll Blut und Wunden",
    "Helft mir Gott's Güte preisen",
    "Ich ruf' zu dir, Herr Jesu Christ",
    "Herr Christ, der ein'ge Gott'ssohn",
    "Ermuntre dich, mein schwacher Geist",
    "Nun ruhen alle Wälder",
    "Wer nur den lieben Gott lässt walten",
    "Herzliebster Jesu, was hast du verbrochen",
    "Jesu Leiden, Pein und Tod",
    "Herzlich lieb hab' ich dich, o Herr",
    "Valet will ich dir geben",
    "Singen wir aus Herzens Grund",
    "Vater unser im Himmelreich",
    "Herzliebster Jesu, was hast du verbrochen",
    "Wer nur den lieben Gott lässt walten",
    "Christus, der uns selig macht",
    "Von Gott will ich nicht lassen",
    "Was mein Gott will, das gescheh' allzeit",
    "Nun lob', mein' Seel', den Herren",
    "Nun ruhen alle Wälder",
    "In dich hab' ich gehoffet, Herr",
    "Christ, unser Herr, zum Jordan kam",
    "Was mein Gott will, das gescheh' allzeit",
    "Werde munter, mein Gemüte",
    "Ist Gott mein Schild und Helfersmann",
    "Helft mir Gott's Güte preisen",
    "Auf, auf, mein Herz, und du mein ganzer",
    "Allein Gott in der Höh' sei Ehr'",
    "Durch Adams Fall ist ganz verderbt",
    "Dies sind die heil'gen zehn Gebot'",
    "Alles ist an Gottes Segen",
    "Keinen hat Gott verlassen",
    "Meine Seele erhebet den Herrn",
    "Liebster Jesu, wir sind hier",
    "Kyrie, Gott Vater in Ewigkeit",
    "Wir glauben all' an einen Gott",
    "Gott der Vater wohn' uns bei",
    "Wer Gott vertraut, hat wohl gebaut",
    "Herr Jesu Christ, dich zu uns wend'",
    "Du, o schönes Weltgebäude",
    "Jesu, meine Freude",
    "Warum sollt' ich mich denn grämen",
    "In allen meinen Taten",
    "Seelen-Bräutigam",
    "Schwing' dich auf zu deinem Gott",
    "In dulci jubilo",
    "Wer in dem Schutz des Höchsten ist",
    "Warum betrübst du dich, mein Herz",
    "Wer nur den lieben Gott lässt walten",
    "Wenn ich in Angst und Not",
    "Uns ist ein Kindlein heut' gebor'n",
    "Nicht so traurig, nicht so sehr",
    "Welt, ade! ich bin dein müde",
    "Meinen Jesum lass' ich nicht, Jesus",
    "Meinen Jesum lass' ich nicht, weil",
    "Alle Menschen müssen sterben",
    "Der du bist drei in Einigkeit",
    "Hilf, Herr Jesu, lass gelingen",
    "Ach Gott, wie manches Herzeleid",
    "Wo Gott zum Haus nicht gibt sein' Gunst",
    "Der Tag, der ist so freudenreich",
    "Als der gütige Gott",
    "Gelobet seist du Jesu Christ",
    "Ihr Gestirn', ihr hohlen Lüfte",
    "Das alte Jahr vergangen ist",
    "Für Freuden lasst uns springen",
    "Du großer Schmerzensmann",
    "O Lamm Gottes, unschuldig",
    "Es stehn vor Gottes Throne",
    "Herr Gott, dich loben alle wir",
    "Heut' ist, o Mensch, ein großer",
    "Jesu, der du selbsten wohl",
    "Nun komm, der Heiden Heiland",
    "Schaut, ihr Sünder",
    "Sei gegrüßet, Jesu gütig",
    "O Herzensangst",
    "Jesus Christus, unser Heiland",
    "Jesus, meine Zuversicht",
    "Erstanden ist der heil'ge Christ",
    "Ach bleib bei uns, Herr Jesu Christ",
    "Das neugeborne Kindelein",
    "Wachet auf, ruft uns die Stimme",
    "Als Jesus Christus in der Nacht",
    "Gott hat das Evangelium",
    "Wär' Gott nicht mit uns diese Zeit",
    "Nun freut euch, lieben Christen, g'mein",
    "Christ lag in Todesbanden",
    "Nun freut euch, Gottes Kinder all'",
    "Ach Gott, erhör' mein Seufzen",
    "Komm, Gott Schöpfer, heiliger Geist",
    "Ich dank' dir schon durch deinen Sohn",
    "Herr Jesu Christ, wahr'r Mensch und Gott",
    "Herr, nun lass in Friede",
    "Von Gott will ich nicht lassen",
    "Gottlob, es geht nunmehr zu Ende",
    "Was bist du doch, o Seele, so betrübet",
    "Liebster Immanuel, Herzog der Frommen",
    "Wie schön leuchtet der Morgenstern",
    "Da der Herr Christ zu Tische saß",
    "Christ ist erstanden",
    "Christus, der uns selig macht",
    "Hilf, Gott, dass mir's gelinge",
    "Christus ist erstanden, hat überwunden",
    "O Mensch, bewein' dein' Sünde groß",
    "O wir armen Sünder",
    "O Mensch, schau Jesum Christum an",
    "Wer weiß, wie nahe mir",
    "Herr Gott, dich loben wir",
    "So gibst du nun, mein Jesu, gute Nacht",
    "Des heil'gen Geistes reiche Gnad'",
    "Als vierzig Tag' nach Ostern",
    "Dir, dir, Jehova, will ich singen",
    "Christe, du Beistand deiner Kreuzgemeine",
    "Weltlich Ehr' und",
    "Herr, ich denk' an jene Zeit",
    "O wie selig seid ihr doch, ihr Frommen",
    "Mitten wir im Leben sind",
    "Verleih' uns Frieden gnädiglich",
    "Es ist genug, so nimm, Herr",
    "Ach Gott, wie manches Herzeleid",
    "Lass, o Herr, dein Ohr sich neigen",
    "O wie selig seid ihr doch, ihr Frommen",
    "Sollt' ich meinem Gott nicht singen",
    "Herr, straf' mich nicht in deinem Zorn",
    "Nun preiset alle",
    "Ich dank' dir, Gott, für all' Wohltat",
    "Das walt' Gott Vater und Gott Sohn",
    "Gott, der du selber bist das Licht",
    "Herr Jesu Christ, du hast bereit",
    "Lobet den Herren, denn er ist sehr freundlich",
    "Danket dem Herren, denn er ist sehr freundlich",
    "Ich danke dir, o Gott, in deinem Throne",
    "Christ, der du bist der helle Tag",
    "Die Nacht ist kommen",
    "Die Sonn' hat sich mit ihrem Glanz",
    "Werde munter, mein Gemüte",
    "Gott lebet noch",
    "Heilig, heilig",
    "O Jesu, du mein Bräutigam",
    "Was betrübst du dich, mein Herze",
    "Es wird schier der letzte Tag",
    "Den Vater dort oben",
    "Nun sich der Tag geendet hat",
    "Was willst du dich, o meine Seele",
    "Wie bist du, Seele",
    "Jesu, du mein liebstes Leben",
    "Jesu, Jesu, du bist mein",
    "Christe, der du bist Tag und Licht",
    "Singt dem Herrn ein neues Lied",
    "Wenn wir in höchsten Nöten sein",
    "Sei Lob und Ehr' dem höchsten Gut",
    "Allein Gott in der Höh' sei Ehr'",
    "Ein' feste Burg ist unser Gott",
    "Ich bin ja, Herr, in deiner Macht",
    "Jesu, nun sei gepreiset",
    "Ach Gott, vom Himmel sieh' darein",
    "Weg, mein Herz, mit den Gedanken",
    "Was frag' ich nach der Welt",
    "Jesu, deine tiefen Wunden",
    "Nun lasst uns Gott, dem Herren",
    "Mein' Augen schließ' ich jetzt",
    "Verleih' uns Frieden gnädiglich",
    "Es ist gewisslich an der Zeit",
    "Christ lag in Todesbanden",
    "Ach Gott, vom Himmel sieh' darein",
    "Jesu, meine Freude",
    "Jesu, meines Herzens Freud'",
    "Was mein Gott will, das gescheh' allzeit",
    "Herr Jesu Christ, du höchstes Gut",
    "Vater unser im Himmelreich",
    "Nun lob', mein' Seel', den Herren",
    "Jesu, der du meine Seele",
    "Befiehl du deine Wege",
    "Gib dich zufrieden und sei stille",
    "Ich dank' dir, lieber Herre",
    "Ein' feste Burg ist unser Gott",
    "O Ewigkeit, du Donnerwort",
    "O Welt, sieh hier dein Leben",
    "Lobt Gott, ihr Christen, allzugleich",
    "Herzlich lieb hab' ich dich, o Herr",
    "Wie schön leuchtet der Morgenstern",
    "Ach Gott und Herr",
    "Eins ist not! ach Herr, dies Eine",
    "Wo soll ich fliehen hin",
    "Freu' dich sehr, o meine Seele",
    "Jesu, meine Freude",
    "Herr Jesu Christ, wahr'r Mensch und Gott",
    "Wär' Gott nicht mit uns diese Zeit",
    "Befiehl du deine Wege",
    "Herr, ich habe missgehandelt",
    "Gelobet seist du Jesu Christ",
    "Nun ruhen alle Wälder",
    "Es ist das Heil uns kommen her",
    "Was frag' ich nach der Welt",
    "Nimm von uns, Herr, du treuer Gott",
    "Was Gott tut, das ist wohlgetan",
    "Herr Jesu Christ, du höchstes Gut",
    "Herr Jesu Christ, mein's Lebens Licht",
    "Nun lob', mein' Seel', den Herren",
    "Jesu, der du meine Seele",
    "Weg, mein Herz, mit den Gedanken",
    "Meinen Jesum lass' ich nicht",
    "Warum betrübst du dich, mein Herz",
    "Ach lieben Christen, seid getrost",
    "Hilf, Gott, dass mir's gelinge",
    "Herr Christ, der ein'ge Gott'ssohn",
    "Auf meinen lieben Gott",
    "Wie schön leuchtet der Morgenstern",
    "O Mensch, bewein' dein' Sünde groß",
    "Christus, der uns selig macht",
    "Ach Gott, wie manches Herzeleid",
    "Ein Lämmlein geht und trägt die Schuld",
    "Mach's mit mir, Gott, nach deiner Güt'",
    "Dank sei Gott in der Höhe",
    "O Gott, du frommer Gott",
    "Allein Gott in der Höh' sei Ehr'",
    "Das alte Jahr vergangen ist",
    "O Gott, du frommer Gott",
    "Christus, der ist mein Leben",
    "Herr, wie du willst, so schick's mit mir",
    "Herr, wie du willst, so schick's mit mir",
    "Sanctus, Sanctus Dominus Deus Sabaoth",
    "Gott sei uns gnädig und barmherzig",
    "Wir Christenleut'",
    "Wenn mein Stündlein vorhanden ist",
    "Wie schön leuchtet der Morgenstern",
    "Jesu, meine Freude",
    "Mit Fried' und Freud' fahr' ich dahin",
    "Allein Gott in der Höh' sei Ehr'",
    "Jesu, nun sei gepreiset",
    "Liebster Jesu, wir sind hier",
    "Sei Lob und Ehr' dem höchsten Gut",
    "Nun danket alle Gott",
    "Wo soll ich fliehen hin",
    "Von Gott will ich nicht lassen",
    "Es woll' uns Gott genädig sein",
    "Für deinen Thron tret' ich hiermit",
    "Es ist das Heil uns kommen her",
    "Wo Gott der Herr nicht bei uns hält",
    "O Gott, du frommer Gott",
    "Jesus, meine Zuversicht",
    "Wer nur den lieben Gott lässt walten",
    "Befiehl du deine Wege",
    "Ich dank' dir, lieber Herre",
    "Lobt Gott, ihr Christen, allzugleich",
    "Nun lieget alles unter dir",
    "Vom Himmel hoch da komm' ich her",
    "O Haupt voll Blut und Wunden",
    "Meines Lebens letzte Zeit",
    "Was Gott tut, das ist wohlgetan",
    "Meinen Jesum lass' ich nicht",
    "Ich hab' in Gottes Herz und Sinn",
    "Jesu, meiner Seelen Wonne",
    "Wenn mein Stündlein vorhanden ist",
    "Es woll' uns Gott genädig sein",
    "Der Herr ist mein getreuer Hirt",
    "Sei Lob und Ehr' dem höchsten Gut",
    "Nun ruhen alle Wälder",
    "Jesu, meine Freude",
    "Warum sollt' ich mich denn grämen",
    "Meine Seele erhebt den Herren",
    "Allein zu dir, Herr Jesu Christ",
    "Wir Christenleut'",
    "Du Lebensfürst, Herr Jesu Christ",
    "Es ist gewisslich an der Zeit",
    "O Welt, sieh hier dein Leben",
    "Von Gott will ich nicht lassen",
    "Jesu, meiner Seelen Wonne",
    "O Welt, sieh hier dein Leben",
    "Befiehl du deine Wege",
    "Hilf, Herr Jesu, lass gelingen",
    "Jesu, der du meine Seele",
    "Kommt her zu mir, spricht Gottes Sohn",
    "Christ lag in Todesbanden",
]

analysis_titles = [
    None,
    "Aus meines Herzens Grunde",
    "Ich dank dir, lieber Herre",
    "Ach Gott, vom Himmel sieh' darein",
    "Es ist das Heil uns kommen her",
    "An Wasserflüssen Babylon",
    "Christus, der ist mein Leben",
    "Nun lob, mein Seel, den Herren",
    "Freuet euch, ihr Christen alle",
    "Ermuntre dich, mein schwacher Geist",
    "Aus tiefer Not schrei ich zu dir 1",
    "Jesu, nun sei gepreiset",
    "Puer natus in Bethlehem",
    "Allein zu dir, Herr Jesu Christ",
    "O Herre Gott, dein göttlich Wort",
    "Christ lag in Todesbanden",
    "Es woll uns Gott genädig sein",
    "Erschienen ist der herrliche Tag",
    "Menschenkind, merk eben",
    "Ich hab mein Sach Gott heimgestellt",
    "Ein feste Burg ist unser Gott",
    "Herzlich tut mich verlangen",
    "Schmücke dich, o liebe Seele",
    "Helft mir Gotts Güte preisen",
    "Valet will ich dir geben",
    "Wo soll ich fliehen hin",
    "O Ewigkeit, du Donnerwort",
    "Es spricht der Unweisen Mund",
    "Nun komm, der Heiden Heiland",
    "Wie nach einer Wasserquelle",
    "Jesus Christus, unser Heiland, der von uns den Gottes Zorn wandt",
    "Wo Gott der Herr nicht bei uns hält",
    "Nun danket alle Gott",
    "Herr, ich habe mißgehandelt",
    "Erbarm dich mein, o Herre Gott",
    "Gott des Himmels und der Erden",
    "Nun bitten wir den heiligen Geist",
    "Wachet doch, erwacht, ihr Schläfer",
    "Straf' mich nicht in deinem Zorn",
    "Ach, was soll ich Sünder machen",
    "Ach Gott und Herr, wie groß und schwer",
    "Was mein Gott will, das g'scheh allzeit",
    "Du Friedefürst, Herr Jesu Christ",
    "Liebster Gott, wann werd ich sterben",
    "Mach's mit mir, Gott, nach deiner Güt",
    "Kommt her zu mir, spricht Gottes Söhn",
    "Vom Himmel hoch, da komm ich her",
    "Vater unser im Himmelreich",
    "Ach wie nichtig, ach wie flüchtig",
    "Mit Fried und Freud ich fahr dahin",
    "O Welt, ich muß dich lassen",
    "Gelobet seist du, Jesu Christ",
    "Wenn mein Stündlein vorhanden ist",
    "Das neugeborne Kindelein",
    "Lobt Gott, ihr Christen, allzugleich",
    "Wir Christenleut'",
    "Christum wir sollen loben schon",
    "O Traurigkeit",
    "Herzlich lieb hab' ich dich, o Herr",
    "Herzliebster Jesu, was hast du",
    "Ich freue mich in dir",
    "Jesu Leiden, Pein und Tod",
    "Wer nur den lieben Gott laesst walten",
    "O Welt, sieh hier dein Leben",
    "Freu dich sehr, o meine Seele",
    "Was Gott thut, das ist wohlgethan",
    "Christ, unser Herr, zum Jordan kam",
    "Freu dich sehr, o meine Seele",
    "Wenn wir in höchsten Nöten sein",
    "Komm, heiliger Geist. Herre Gott",
    "Gott sei gelobet und gebenedeiet",
    "Ich ruf' zu dir, Herr Jesu Christ",
    "Erhalt uns, Herr, bei deinem Wort",
    "Herr Jesu Christ, du höchstes Gut",
    "O Haupt voll Blut und Wunden",
    "Das walt' mein Gott",
    "Freu' dich sehr, o meine Seele",
    "In dich hab' ich gehoffet, Herr'",
    "Herzliebster Jesu, was hast du",
    "Heut' triumphiret Gottes Sohn",
    "O Haupt voll Blut und Wunden",
    "Christus, der uns selig macht",
    "O großer Gott von Macht",
    "Jesu Leiden, Pein und Tod",
    "Nun bitten wir den heiligen Geist",
    "O Gott, du frommer Gott",
    "Wie schön leuchtet der Morgenstern",
    "Du, o schönes Weltgebäude",
    "helft mir Gott's Güte preisen",
    "O Haupt voll Blut und Wunden",
    "Hast du denn, Jesu, dein Angesight",
    "Verleih' uns Frieden gnädiglich",
    "O Jesu Christ, du höchstes Gut",
    "Wach' auf, mein Herz",
    "Warum betrübst du dich, mein Herz",
    "Werde munter, mein Gemüte",
    "Jesu, meine Freude",
    "Nun bitten wir den heiligen Geist",
    "O Haupt voll Blut and Wunden",
    "Helft mir Gott's Güte preisen",
    "Durch Adams Fall ist ganz verderbt",
    "Herr Christ, der ein'ge Gott's-Sohn",
    "Ermuntre dich, mein schwacher Geist",
    "Nun ruhen alle Wälder",
    "Wer nun den lieben Gott lässt walten",
    "Herzliebster Jesu, was hast du verbrochen",
    "Jesu Leiden, Pein und Tod",
    "Herzlich lieb hab' ich dich, o Herr",
    "Valet will ich dir geben",
    "Singen wir aus Herzens Grund",
    "Vater unser in Himmelreich",
    "Herzliebster Jesu, was hast du verbrochen",
    "Wer nur den lieben Gott lässt walten",
    "Christus, der uns selig macht",
    "Von Gott will ich nicht lassen",
    "das Was mein Gott will",
    "Nun lob', mein' Seel', den Herren",
    "Nun ruhen alle Wälder",
    "In dich hab' ich gehoffet, Herr",
    "Christ, unser Herr, zum Jordan kam",
    "Was mein Gott will, das g'scheh' allzeit",
    "Werde munter, mein Gemüte",
    "Ist Gott mein Schild und Helfersmann",
    "Helft mir Gott's Güte preisen",
    "Auf, auf, mein Herz, und du mein ganzer Sinn",
    "Allein Gott in der Höh' sei Ehr'",
    "Durch Adams Fall ist ganz verderbt",
    "Dies sind die heil'gen zehn Gebot",
    "Alles ist an Gottes Segen",
    "Keinen hat Gott verlassen",
    "Meine Seele erhebet den Herrn",
    "Liebster Jesu, wir sind hier",
    "Kyrie, Gott Vater in Ewegkeit",
    "Wir glauben all' an einem Gott",
    "Du, o schönes Weltgebäude",
    "Gott der Vater wohn' uns bei",
    "Herr Jesu Christ, dich zu uns wend'",
    "Wer Gott vertraut, hat wohl gebaut",
    "Jesu, meine Freude",
    "Warum sollt ich mich denn grämen",
    "In allen meinen Taten",
    "Seelen-Bräutigam",
    "Schwing' dich auf zu deinem Gott",
    "In dulci jubilo",
    "Wer in dem Schutz des Höchsten",
    "Warum betrübst du dich",
    "Wer nur den lieben Gott lässt walten",
    "Wenn ich in Angst und Not",
    "Uns ist ein Kindlein heut' gebor'n",
    "Nicht so traurig, nicht so sehr",
    "Welt, ade! ich bin dein mude",
    "Meinen Jesum laß' ich nicht, Jesus",
    "Meinen Jesum laß' ich nicht, Weil",
    "Alle Menschen müssen sterben",
    "Der du bist drei in Einigkeit",
    "Hilf, Herr Jesu, laß gelingen",
    "Ach Gott, wie manches Herzeleid",
    "Wo Gott zum Haus nicht gibt",
    "Der Tag, der ist so freudenreich",
    "Als der gütige Gott",
    "Gelobet seist du, Jesu Christ",
    "Ihr Gestirn', ihr hohlen Lüfte",
    "Das alte Jahr vergangen ist",
    "Für Freuden laßt uns springen",
    "Herr Gott, dich loben alle wir",
    "O Lamm Gottes, unschuldig",
    "Es stehn vor Gottes Throne",
    "Du großer Schmerzensmann",
    "Heut' ist, o Mensch, ein großer",
    "Jesu, der du gelbsten wohl",
    "Nun komm, der Heiden Heiland",
    "Schaut, ihr Sünder",
    "Sei gegrüßet, Jesu gütig",
    "O Herzensangst",
    "Jesus Christus, unser Heiland, der den Tod",
    "Jesus, meine Zuversicht",
    "Erstanden ist der heil'ge Christ",
    "Ach bleib bei uns, Herr Jesu Christ",
    "Das neugeborne Kindelein",
    "Wachtet auf, ruft uns die Stimme",
    "Als Jesus Christus in der Nacht",
    "Gott hat das Evangelium",
    "Wär' Gott night mitt uns diese Zeit",
    "Nun freut euch, lieben Christen, g'mein",
    "Christ lag in Todesbanden",
    "Nun fret euch, Gottes Kinder all'",
    "Ach Gott, erhör mein Seufzen",
    "Komm, Gott Schöpfer, heiliger Geist",
    "Ich dank' dir schon durch deinen Sohn",
    "Herr Jesu Christ, wahr'r Mensch und Gott",
    "Herr, nun laß in Frieden",
    "Von Gott will ich nicht lassen",
    "Gottlob, es geht nunmehr zu Ende",
    "Was bist du doch, o Seele, so betrübet",
    "Liebster Immanuel, Herzog der Frommen",
    "Wie schön leuchtet der Morgenstern",
    "Da der Herr Christ zu Tische saß",
    "Christ ist erstanden/Wär er nicht erstanden/Alleluja",
    "Christus, der uns selig macht",
    "Hilf, Gott, daß mir's gelinge",
    "Christus ist erstanden, hat überwunden",
    "O Mensch, bewein' dein' Sünde groß",
    "O wir armen Sünder",
    "O Mensch, schau Jesum Christum an",
    "Wir weiß, wie nahe mir",
    "Herr Gott, dich loben wir [Te Deum]",
    "So gibst du nun, mein Jesu, gute Nacht",
    "Das heil'gen Geistes reiche Gnad'",
    "Als vierzig Tag' nach Ostern",
    "Dir, dir, Jehovah, will ich singen",
    "Christe, du Beistand deiner Kruzgemeine",
    "Weltlich Ehr' und zeitlich Gut",
    "Herr, ich denk' an jene Zeit",
    "O wie selig seid ihr doch, ihr Frommen",
    "Mitten wir im Leben sind",
    "Verleih' uns Frieden gnädlich",
    "Es ist genug; so nimm, Herr",
    "Ach Gott, wie manches Herzeleid",
    "Laß, o Herr, dein Ohr sich neigen",
    "O wie selig seid ihr doch, ihr Frommen",
    "Sollt' ich meinem Gott nicht singen",
    "Herr, straf mich nicht in deinem Zorn",
    "Nun priset alle",
    "Ich dank dir, Gott, für all' Wohltat",
    "???",
    "Gott, der du selber bist das Licht",
    "Herr Jesu Christ, du hast bereit",
    "Lobet den Herren, denn er ist sehr freundlich",
    "Danket dem Herren, denn er ist sehr freundlich",
    "Ich danke dir, o Gott, in deinem Throne",
    "Christ, der du  bist der helle Tag",
    "Die Nacht is kommen",
    "Die Sonn' hat sich mit ihrem Glanz",
    "Werde munter, mein Gemüte",
    "Gott lebet noch",
    "Heilig, heilig",
    "O Jesu, du mein Bräutigan",
    "Was betrübst du dich, mein Herze",
    "Es wird schier der letzte Tag",
    "Den Vater dort oben",
    "Nun sich der Tag geendet hat",
    "Was willst du dich, o meine Seele",
    "Wie bist du, Seele",
    "Jesu, du mein liebstes Leben",
    "Jesu, Jesu, du bist mein",
    "Christe, der du bist Tag und Licht",
    "Singt dem Herrn ein neues Lied",
    "Wenn wir in höchsten Nöten sein",
    "Sei Lob und Ehr den höchsten Gut",
    "Allein Gott in der Höh' sei Ehr",
    "Ein' feste Burg ist unser Gott",
    "Ich bin ja, Herr, in deiner Macht",
    "Jesu, nun sei gepreiset",
    "Ach Gott, vom Himmel sieh' darein",
    "Weg, mein Herz, mit den Gedanken",
    "Was frag' ich nach der Welt",
    "Jesu, deine tiefen Wunden",
    "Nun aßt uns Gott, dem Herren",
    "Meine Augen schließ' ich jetzt",
    "Verleih' uns Frieden gnädiglich",
    "Es ist gewisslich an der Zeit",
    "Christ lag in Todesbanden",
    "Ach Gott, vom Himmel sieh' darein",
    "Jesu, meine Freude",
    "Jesu, meines Herzens Freud'",
    "das Was mein Gott will",
    "Herr Jesu Christ, du höchstes Gut",
    "Vater unser im Himmelreich",
    "Non lob', mein Seel', den Herren",
    "Jesu, der du meine Seele",
    "Befiehl du deine Wege",
    "Gib dich zufrieden und sei stille",
    "Ich dank' dir, lieber Herre",
    "Ein' feste Burg ist unser Gott",
    "O Ewigkeit, du Donnerwort",
    "O Welt, sieh hier dein Leben",
    "Lobt Gott, ihr Christen, allzugleich",
    "Herzlich lieb hab' ich dich, o Herr",
    "Wie schön leuchtet der Morgenstern",
    "Ach Gott und Herr",
    "Eins ist not! ach Herr, dies Eine",
    "Wo soll ich fliehen hin",
    "Freu' dich sehr, o meine Seele",
    "Jesu, meine Freude",
    "Herr Jesu Christ, wahr'r Mensch und Gott",
    "Wär' Gott nicht mit uns diese Zeit",
    "Befiehl du deine Wege",
    "Herr, ich habe mißgehandelt",
    "Gelobet seist du, Jesu Christ",
    "Nun ruhen alle Wälder",
    "Es ist das Heil uns kommen her",
    "Was frag' ich nach der Welt",
    "Nimm von uns, Herr, du treuer Gott",
    "Was Gott tut, das ist wohlgetan",
    "Herr Jesu Christ, du höchstes Gut",
    "Herr Jesu Christ, mein's Lebens nicht",
    "Nun lob', mein Seel', den Herren",
    "Jesu, der du meine Seele",
    "Weg, mein Herz, mit den Gedanken",
    "Meinen Jesum laß ich nicht",
    "Warum betrübst du dich, mein Herz",
    "Ach lieben Christen, seid getrost",
    "Hilf, Gott, daß mir's gelinge",
    "Herr Christ, der ein'ge Gott's sohn",
    "Auf meinen lieben Gott",
    "Wie schön leuchtet der Morgenstern",
    "O Mensch, bewein' dein' Sünde groß",
    "Christus, der uns selig macht",
    "Ach Gott, wie manches Herzeleid",
    "Ein Lämmlein geht und trägt die Schuld",
    "Mach's mit mir, Gott, nach deiner",
    "Dank sei Gott in der Höhe",
    "O Gott, du frommer Gott",
    "Allein Gott in der Höh sei Ehr",
    "Das alte Jahr vergangen ist",
    "O Gott, du frommer Gott",
    "Christus, der ist mein Leben",
    "Herr, wie du willst, so schick's mit mir",
    "Herr, wie du willst so schick's mit mir",
    "Sanctus, Sanctus Dominus Deus Sabaoth",
    "Gott sei uns gnädig und harmherzig",
    "Wir Christenleut'",
    "Wenn mein Stündlein vorhanden ist",
    "Wie schön leuchtet der Morgenstern",
    "Jesu, meine Freude",
    "Mit Fried' und Freud' ich fahr' dahin",
    "Allein Gott in der Höh' sei Ehr'",
    "Jesu, nun sei gepreiset",
    "Liebster Jesu, wir sind hier",
    "Sei Lob und Ehr' dem höchsten Gut",
    "Nun danker alle Gott",
    "Wo soll ich fliehen hin",
    "Von Gott will ich nicht lassen",
    "Es woll uns Gott genädig sein",
    "Für deinen Thron tret' ich hiermit",
    "Es ist das Heil uns kommen her",
    "Wo Gott der Herr nicht bei uns hält",
    "O Gott, du frommer Gott",
    "Jesus, meine Zuversicht",
    "Wer nur den lieben Gott lässt walten",
    "Befiehl du deine Wege",
    "Ich dank' dir, lieber Herre",
    "Lobt Gott, ihr Christen, allzugleich",
    "Nun lieget alles unter dir",
    "Vom Himmel hoch, da komm' ich her",
    "O Haupt voll Blut und Wunden",
    "Meines Lebens letzte Zeit",
    "Was Gott tut, das ist wohlgetan",
    "Meinen Jesum laß ich nicht",
    "Ich hab' in Gottes Herz und Sinn",
    "Jesu, meiner Seelen Wonne",
    "Wenn mein Stündlein vorhanden ist",
    "Es woll' uns Gott genädig sein",
    "Allein Gott in der Höh sei Ehr",
    "Sei Lob und Ehr den höchsten Gut",
    "Nun ruhen alle Wälder",
    "Jesu, meine Freude",
    "Warum sollt' ich mich denn grämen",
    "Meine Seel' erhebt den Herren",
    "Allein zu dir, Herr Jesu Christ",
    "Wir Christenleut'",
    "Ermuntre dich, mein schwacher Geist",
    "Es ist gewisslich an der Zeit",
    "O Welt, sieh hier dein Leben",
    "Von Gott will ich nicht lassen",
    "Jesu, meiner Sellen Wonne",
    "O Welt, sieh heir dein Leben",
    "Befiehl du deine Wege",
    "Hilf, Herr Jesu, laß gelingen",
    "Jesu, der du meine Seele",
    "Kommt her zu mir, spricht Gottes Sohn",
    "Christ lag in Todesbanden",
]


def levenshtein_distance(s, t):
    """
    Calculate Levenshtein distance for two strings.
    See `flexible_levenshtein_distance()` for tests and comparison.
    """
    m = len(s)
    n = len(t)
    d = [[0] * (n + 1) for i in range(m + 1)]

    for i in range(1, m + 1):
        d[i][0] = i

    for j in range(1, n + 1):
        d[0][j] = j

    for j in range(1, n + 1):
        for i in range(1, m + 1):
            if s[i - 1] == t[j - 1]:
                cost = 0
            else:
                cost = 1
            d[i][j] = min(d[i - 1][j] + 1,  # deletion
                          d[i][j - 1] + 1,  # insertion
                          d[i - 1][j - 1] + cost)  # substitution

    return d[m][n]


def flexible_levenshtein_distance(
        str1: str,
        str2: str,
        use_shorter_length: bool = True,
        case_matters: bool = False,
        ignore_characters: str = ".,:;'"
) -> int:
    """
    Compare two strings (here chorale titles) with the Levenshtein distances,
    but with flexibilty to certain known deviations.

    For example, the presence or absence of inverted commas:

    >>> w = "Ich hab' mein' Sach'"
    >>> without = "Ich hab mein Sach"
    >>> levenshtein_distance(w, without)
    3

    >>> flexible_levenshtein_distance(w, without, ignore_characters="'")
    0

    And in the comparison of shorter vs full titles as in the following:

    >>> full = "Ich hab mein Sach Gott heimgestellt"
    >>> levenshtein_distance(full, without)
    18

    >>> flexible_levenshtein_distance(full, without, use_shorter_length=True)
    0

    Also helps to omit verse numbers and other parenthetic ends,
    ... but only a bit if there are other divergences earlier on as in the following:

    >>> short = "Du Friedensfürst, Herr Jesu Christ"
    >>> long = "Du Friedefürst, Herr Jesu Christ (v. 1)"  # NB not "Friedens"

    >>> levenshtein_distance(short, long)  # 7 + 2
    9

    >>> flexible_levenshtein_distance(short, long, use_shorter_length=True)
    4

    :param str1: string 1 to compare with ...

    :param str2: string 2.

    :param use_shorter_length: bool. If True, take the shorter string length and only compare
    with that much of the longer string. Useful when you expect partial-vs-complete comparisons.
    first part of the N charac

    :param case_matters: bool. False by default. If True then ignore case differences ("a" = "A").

    :param ignore_characters: A string of all the characters to ignore, e.g., punctuation. Runs
    before case_matters as characters to ignore may be case-sensitive.

    :return: int

    """

    if str1 == str2:  # worth checking!
        return 0

    if ignore_characters:
        for c in ignore_characters:
            str1 = str1.replace(c, "")
            str2 = str2.replace(c, "")

    if use_shorter_length:
        min_len = min(len(str1), len(str2))
        str1 = str1[:min_len]
        str2 = str2[:min_len]

    if not case_matters:
        str1 = str1.lower()
        str2 = str2.lower()

    return levenshtein_distance(str1, str2)


def catalogue_convert(
        in_entry: str,
        in_cat: str = "Riemenschneider",
        out_cat: str = "text",
) -> str:
    """
    Convert from one catalogue reference to another.
    E.g., to get the text (name / title) from a Riemenschneider number:

    >>> catalogue_convert("1", in_cat="Riemenschneider", out_cat="text")
    'Aus meines Herzens Grunde'

    and vice versa:

    >>> catalogue_convert("Aus meines Herzens Grunde", in_cat="text", out_cat="Riemenschneider")
    '1'

    """

    in_col = col_dict[in_cat]  # raises error if not there
    out_col = col_dict[out_cat]  # "

    for row in catalogue:
        if row[in_col] == in_entry:
            return row[out_col]

    return ""



def compare_titles_with_catalogue(titles: List[str],
                                  in_cat="Riemenschneider",
                                  out_cat="title",
                                  threshold=6
                                  ):

    errors = 0

    for i, title  in enumerate(titles, 1):
        title = score_titles[i]
        catalogue_title = catalogue_convert(str(i), in_cat=in_cat, out_cat=out_cat)

        if catalogue_title is None:
            catalogue_title = ""

        d = flexible_levenshtein_distance(title, catalogue_title)

        if d > threshold:
            print(i, d, title, "///", catalogue_title)
            errors += 1
        else:
            print(i)

    print(errors)

    return errors




def compare_score_and_catalogue():
    """
    Compare a list of titles on the scores with those in the catalogue
    with the hypothesis that the catalogue is CPE.
    """
    global score_titles
    return compare_titles_with_catalogue(score_titles[1:],
                                         in_cat="CPE",
                                         threshold=3)


def compare_analysis_and_catalogue():
    """
    Compare a list of titles on the analyses with those in the catalogue
    with the hypothesis that the catalogue is Riemenschneider.
    """
    global score_titles
    return compare_titles_with_catalogue(score_titles[1:])

# ------------------------------------------------------------------------------

if __name__ == "__main__":
    import doctest
    doctest.testmod()
