"""
Functionality for checking
- score titles (extracted from the source "*.mscz" files) against ...
- the catalogue for which the external source is that kindly curated by the Wikipedia community:
https://en.wikipedia.org/wiki/List_of_chorale_harmonisations_by_Johann_Sebastian_Bach#Numbering_conventions

Uses a modified form of the Levenshtein distance (see code / docs below).

Also, for good measure, check those of
the corresponding analyses (Riemenschneider numbering)
stored in the "When in Rome" meta corpus:
https://github.com/MarkGotham/When-in-Rome/

"""
from typing import List

catalogue = [
    # ['Text', 'Tune', 'Zahn', 'BWV', 'CPE', 'Riemenschneider'],
    ['Aus meines Herzens Grunde', 'Aus meines Herzens Grunde', '5269', '269', 1, 1],
    ['Ich dank dir, lieber Herre', 'Ich dank dir, lieber Herre', '5354b', '347', 2, 2],
    ['Schau, lieber Gott, wie meine Feind (1)', 'Ach Gott, vom Himmel sieh darein', '4431', '153.1', 3, 3],
    ['Es ist das Heil uns kommen her (11)', 'Es ist das Heil uns kommen her', '4430', '86.6', 4, 4],
    ['An Wasserflüssen Babylon (for B308)', 'An Wasserflüssen Babylon', '7663', '267', 5, 5],
    ['Christus, der ist mein Leben', 'Christus, der ist mein Leben', '132', '281', 7, 6],
    ['Nun lob, mein Seel, den Herren (3)', 'Nun lob, mein Seel, den Herren', '8244', '17.7', 6, 7],
    ['Freuet euch, ihr Christen alle (4)', 'Freuet euch, ihr Christian alle', '7880a', '40.8', 8, 8],
    ['Ermuntre dich, mein schwacher Geist (9)', 'Ermuntre dich, mein schwacher Geist', '5741', '248.12', 9, 9],
    ['Aus tiefer Not schrei ich zu dir (5)', 'Aus tiefer Not schrei ich zu dir (melody #1)', '4437', '38.6', 10, 10],
    ['Jesu, nun sei gepreiset (3)', 'Jesu, nun sei gepreiset', '8477a', '41.6', 11, 11],
    ['Ein Kind geborn zu Bethlehem (4)', 'Ein Kind geborn zu Bethlehem (Puer natus in Bethlehem)', '192b', '65.2', 12, 12],
    ['Allein zu dir, Herr Jesu Christ (4)', 'Allein zu dir, Herr Jesu Christ', '7292b', '33.6', 13, 13],
    ['O Herre Gott, dein göttlich Wort (8)', 'O Herre Gott, dein göttlich Wort', '5690', '184.5', 14, 14],
    ['Christ lag in Todesbanden', 'Christ lag in Todesbanden', '7012a', '277', 15, 15],
    ['Es woll uns Gott genädig sein', 'Es woll uns Gott genädig sein', '7247', '311', 16, 16],
    ['Erschienen ist der herrlich Tag (14)', 'Erschienen ist der herrlich Tag', '1743', '145.5', 17, 17],
    ['Gottes Sohn ist kommen', 'Menschenkind merk eben', '3294', '318', 18, 18],
    ['Ich hab mein Sach Gott heimgestellt', 'Ich hab mein Sach Gott heimgestellt', '1678', '351', 19, 19],
    ['Ein feste Burg ist unser Gott', 'Ein feste Burg ist unser Gott', '7377', '302', 20, 20],
    ['Befiehl du deine Wege (5)', 'Befiehl du deine Wege (melody #1)', '5385a', '153.5', 21, 21],
    ['Schmücke dich, o liebe Seele (9)', 'Schmücke dich, o liebe Seele', '6923', '180.7', 22, 22],
    ['Helft mir Gotts Güte preisen (6)', 'Helft mir Gotts Güte preisen', '5267', '28.6', 23, 23],
    ['Valet will ich dir geben', 'Valet will ich dir geben', '5404a', '415', 24, 24],
    ['Auf meinen lieben Gott (5?)', 'Wo soll ich fliehen hin', '2164', '148.6', 25, 25],
    ['O Ewigkeit, du Donnerwort (11)', 'O Ewigkeit, du Donnerwort', '5820', '20.7=20.11', 26, 26],
    ['Es spricht der Unweisen Mund wohl', 'Es spricht der Unweisen Mund wohl', '4436', '308', 27, 27],
    ['Nun komm, der Heiden Heiland (8)', 'Nun komm, der Heiden Heiland', '1174', '36.8', 28, 28],
    ['Weg, mein Herz, mit den Gedanken (12)', 'Freu dich sehr, o meine Seele', '6543', '32.6', 29, 29],
    ['Jesus Christus, unser Heiland, der von uns', 'Jesus Christus, unser Heiland, der von uns', '1576', '363', 30, 30],
    ['Ach, lieben Christen, seid getrost', 'Wo Gott der Herr nicht bei uns hält', '4441a', '256', 31, 31],
    ['Nun danket alle Gott', 'Nun danket alle Gott', '5142', '386', 32, 32],
    ['Herr, ich habe missgehandelt', 'Herr, ich habe missgehandelt', '3695', '330', 35, 33],
    ['Erbarm dich mein, o Herre Gott', 'Erbarm dich mein, o Herre Gott', '5851', '305', 33, 34],
    ['Ihr Gestirn, ihr hohlen Lüfte (9)', 'Gott des Himmels und der Erden', '3614', '248.53', 34, 35],
    ['Nun bitten wir den Heiligen Geist', 'Nun bitten wir den Heiligen Geist', '2029', '385', 36, 36],
    ['Jesu, der du meine Seele', 'Jesu, der du meine Seele', '6804', '352', 37, 37],
    ['Mache dich, mein Geist, bereit (10)', 'Straf mich nicht in deinem Zorn', '6274a', '115.6', 38, 38],
    ['Ach, was soll ich Sünder machen', 'Ach, was soll ich Sünder machen', '3573b', '259', 39, 39],
    ['Ach Gott und Herr', 'Ach Gott und Herr', '2051', '255', 40, 40],
    ['Ich hab in Gottes Herz und Sinn (10)', 'Was mein Gott will, das gscheh allzeit', '7568', '65.7', 41, 41],
    ['Du Friedefürst, Herr Jesu Christ (1)', 'Du Du Friedefürst, Herr Jesu Christ', '4373', '67.7', 42, 42],
    ['Liebster Gott, wenn werd ich sterben (5)', 'Liebster Gott, wenn werd ich sterben', '6634', '8.6', 43, 43],
    ['Machs mit mir, Gott, nach deiner Güt', 'Machs mit mir, Gott, nach deiner Güt', '2383', '377', 44, 44],
    ['Gott Vater, sende deinen Geist (10)', 'Kommt her zu mir, spricht Gottes Sohn', '2496c', '108.6', 46, 45],
    ['Vom Himmel hoch da komm ich her (13)', 'Vom Himmel hoch da komm ich her', '346', '248.09', 45, 46],
    ['Vater unser im Himmelreich', 'Vater unser im Himmelreich', '3561', '416', 47, 47],
    ['Ach wie flüchtig, ach wie nichtig (8)', 'Ach wie flüchtig, ach wie nichtig', '1887', '26.6', 48, 48],
    ['Mit Fried und Freud ich fahr dahin', 'Mit Fried und Freud ich fahr dahin', '3986', '382', 49, 49],
    ['O Welt, sieh hier dein Leben (3)', 'O Welt, ich muss dich lassen', '2293b', '244.37', 50, 50],
    ['Gelobet seist du, Jesu Christ (7)', 'Gelobet seist du, Jesu Christ', '1947', '91.6', 53, 51],
    ['Wenn mein Stündlein vorhanden ist', 'Wenn mein Stündlein vorhanden ist', '4482ab', '429', 51, 52],
    ['Das neugeborne Kindelein (4)', 'Das neugeborne Kindelein', '491', '122.6', 52, 53],
    ['Lobt Gott, ihr Christen, allzugleich (8)', 'Kommt her, ihr lieben Schwesterlein', '198', '151.5', 54, 54],
    ['Wir Christenleut habn jetzund Freud (5)', 'Wir Christenleut habn jetzund Freud', '2072', '110.7', 57, 55],
    ['Christum wir sollen loben schon (8)', 'Christum wir sollen loben schon', '297', '121.6', 55, 56],
    ['O Traurigkeit, o Herzeleid!', 'O Traurigkeit, o Herzeleid!', '1915', '404', 60, 57],
    ['Herzlich lieb hab ich dich, o Herr (1)', 'Herzlich lieb hab ich dich, o Herr', '8326', '174.5', 56, 58],
    ['Herzliebster Jesu, was hast du verbrochen (7)', 'Herzliebster Jesu, was hast du verbrochen', '983', '245.03', 58, 59],
    ['Ich freue mich in dir (4)', 'O Gott, du frommer Gott (melody #4)', '5187', '133.6', 61, 60],
    ['Jesu Leiden, Pein und Tod (33)', 'Jesu Kreuz, Leiden und Pein', '6288b', '159.5', 59, 61],
    ['Wer nur den lieben Gott lässt walten (7)', 'Wer nur den lieben Gott lässt walten', '2778', '197.10', 66, 62],
    ['O Welt, sieh hier dein Leben (3,4)', 'O Welt, ich muss dich lassen', '2293b', '245.11', 62, 63],
    ['Treuer Gott, ich muss dir klagen (6)', 'Freu dich sehr, o meine Seele', '6543', '194.06', 63, 64],
    ['Was Gott tut, das ist wohlgetan (1)', 'Was Gott tut, das ist wohlgetan', '5629', '144.3', 64, 65],
    ['Christ unser Herr zum Jordan kam', 'Christ unser Herr zum Jordan kam', '7246', '280', 65, 66],
    ['Kommt, lasst euch den Herren lehren (6)', 'Freu dich sehr, o meine Seele', '6543', '39.7', 67, 67],
    ['Wenn wir in höchsten Nöten sein', 'Wenn wir in höchsten Nöten sein', '394', '431', 68, 68],
    ['Komm, Heiliger Geist, Herre Gott (3)', 'Komm, Heiliger Geist, Herre Gott', '7445a', '226.2', 69, 69],
    ['Gott sei gelobet und gebenedeiet', 'Gott sei gelobet und gebenedeiet', '8078', '322', 70, 70],
    ['Ich ruf zu dir, Herr Jesu Christ (5)', 'Ich ruf zu dir, Herr Jesu Christ', '7400', '177.5', 71, 71],
    ['Erhalt uns, Herr, bei deinem Wort (2)', 'Erhalt uns, Herr, bei deinem Wort', '350', '6.6', 72, 72],
    ['Herr Jesu Christ, du höchstes Gut', 'Herr Jesu Christ, du höchstes Gut', '4486', '334', 73, 73],
    ['O Haupt voll Blut und Wunden (1,2)', 'Befiehl du deine Wege (melody #1)', '5385a', '244.54', 74, 74],
    ['Das walt mein Gott, Vater, Sohn und heiliger Geist', 'Das walt mein Gott, Vater, Sohn und heiliger Geist', '4217', '291', 75, 75],
    ['Tröstet, tröstet meine Lieben (3)', 'Freu dich sehr, o meine Seele', '6543', '30.6', 76, 76],
    ['Nun, liebe Seel, nun ist es Zeit (5)', 'In dich hab ich gehoffet, Herr', '2461', '248.46', 77, 77],
    ['Herzliebster Jesu, was hast du verbrochen (1)', 'Herzliebster Jesu, was hast du verbrochen', '983', '244.03', 78, 78],
    ['Heut triumphieret Gottes Sohn', 'Heut triumphieret Gottes Sohn', '2585', '342', 79, 79],
    ['Befiehl du deine Wege (1)', 'Befiehl du deine Wege (melody #1)', '5385a', '244.44', 87, 80],
    ['Christus, der uns selig macht (1)', 'Christus, der uns selig macht', '6285', '245.15', 80, 81],
    ['O großer Gott von Macht (9)', 'O großer Gott von Macht', '5101a', '46.6', 81, 82],
    ['Jesu Leiden, Pein und Tod (10)', 'Jesu Kreuz, Leiden und Pein', '6288b', '245.14', 82, 83],
    ['Nun bitten wir den Heiligen Geist (3)', 'Nun bitten wir den Heiligen Geist', '2029', '197.05', 83, 84],
    ['O Gott, du frommer Gott (2)', 'O Gott, du frommer Gott (melody #3)', '5206b', '45.7', 84, 85],
    ['Wie schön leuchtet der Morgenstern (6)', 'Wie schön leuchtet der Morgenstern', '8359', '36.4', 85, 86],
    ['Du, o schönes Weltgebäude (6)', 'Du geballtes Weltgebäude', '6773', '56.5', 86, 87],
    ['Helft mir Gotts Güte preisen (6)', 'Helft mir Gotts Güte preisen', '5267', '(28.6)', 88, 88],
    ['O Haupt voll Blut und Wunden (9)', 'Befiehl du deine Wege (melody #1)', '5385a', '244.62', 89, 89],
    ['Hast du denn, Jesu, dein Angesicht gänzlich verborgen (6)', 'Hast du denn, Jesu, dein Angesicht gänzlich verborgen', '1912a', '57.8', 90, 90],
    ['Verleih uns Frieden gnädiglich', 'Verleih uns Frieden gnädiglich', '1945', '42.7', 91, 91],
    ['Herr Jesu Christ, du höchstes Gut (8)', 'Herr Jesu Christ, du höchstes Gut', '4486', '168.6', 92, 92],
    ['Wach auf, mein Herz, und singe (9,10)', 'Nun lasst uns Gott dem Herren', '159', '194.12', 93, 93],
    ['Warum betrübst du dich, mein Herz (11)', 'Warum betrübst du dich, mein Herz', '1689', '47.5', 94, 94],
    ['Werde munter mein Gemüte (6)', 'Werde munter mein Gemüte', '6551', '55.5', 95, 95],
    ['Selig ist die Seele (9)', 'Jesu, meine Freude', '8032', '87.7', 96, 96],
    ['Nun bitten wir den Heiligen Geist (3)', 'Nun bitten wir den Heiligen Geist', '2029', '169.7', 97, 97],
    ['O Haupt voll Blut und Wunden (5)', 'Befiehl du deine Wege (melody #1)', '5385a', '244.15', 98, 98],
    ['Helft mir Gotts Güte preisen (6)', 'Helft mir Gotts Güte preisen', '5267', '16.6', 99, 99],
    ['Durch Adams Fall ist ganz verderbt (8)', 'Durch Adams Fall ist ganz verderbt', '7549', '18.5', 100, 100],
    ['Herr Christ, der einge Gottessohn (5)', 'Herr Christ, der einge Gottessohn', '4297a', '164.6', 101, 101],
    ['Du Lebensfürst, Herr Jesu Christ (1, 13)', 'Ermuntre dich, mein schwacher Geist', '5741', '43.11', 102, 102],
    ['In allen meinen Taten (15)', 'O Welt, ich muss dich lassen', '2293b', '13.6', 103, 103],
    ['Wer nur den lieben Gott lässt walten (8)', 'Wer nur den lieben Gott lässt walten', '2778', '88.7', 104, 104],
    ['Herzliebster Jesu, was hast du verbrochen (4)', 'Herzliebster Jesu, was hast du verbrochen', '983', '244.46', 105, 105],
    ['Jesu Leiden, Pein und Tod (20)', 'Jesu Kreuz, Leiden und Pein', '6288b', '245.28', 106, 106],
    ['Herzlich lieb hab ich dich, o Herr (3)', 'Herzlich lieb hab ich dich, o Herr', '8326', '245.40', 107, 107],
    ['Valet will ich dir geben (3)', 'Valet will ich dir geben', '5404a', '245.26', 108, 108],
    ['Singen wir aus Herzensgrund (4)', 'Da Christus geboren war', '4816', '187.7', 109, 109],
    ['So wahr ich lebe, spricht dein Gott (6)', 'Vater unser im Himmelreich', '3561', '102.7', 110, 110],
    ['Herzliebster Jesu, was hast du verbrochen (8,9)', 'Herzliebster Jesu, was hast du verbrochen', '983', '245.17', 111, 111],
    ['Wer weiss, wie nahe mir mein Ende (12)', 'Wer nur den lieben Gott lässt walten', '2778', '84.5', 112, 112],
    ['Christus, der uns selig macht (8)', 'Christus, der uns selig macht', '6285', '245.37', 113, 113],
    ['Von Gott will ich nicht lassen', 'Von Gott will ich nicht lassen', '5264b', '419', 114, 114],
    ['Was mein will, das gscheh allzeit (1)', 'Was mein Gott will, das gscheh allzeit', '7568', '244.25', 115, 115],
    ['Nun lob, mein Seel, den Herren (5)', 'Nun lob, mein Seel, den Herren', '8244', '29.8', 116, 116],
    ['O Welt, sieh hier dein Leben (5)', 'O Welt, ich muss dich lassen', '2293b', '244.10', 117, 117],
    ['In dich hab ich gehoffet, Herr (5)', 'In dich hab ich gehoffet, Herr', '2461', '244.32', 118, 118],
    ['Was alle Weisheit in der Welt (8)', 'Christ unser Herr zum Jordan kam', '7246', '176.6', 119, 119],
    ['Barmherzger Vater, höchster Gott (9)', 'Was mein Gott will, das gscheh allzeit', '7568', '103.6', 120, 120],
    ['Werde munter mein Gemüte (6)', 'Werde munter mein Gemüte', '6551', '244.40', 121, 121],
    ['Ist Gott mein Schild und Helfersmann (4)', 'Ist Gott mein Schild und Helfersmann', '2542', '85.6', 122, 122],
    ['Zeuch ein zu deinen Toren (5)', 'Helft mir Gotts Güte preisen', '5267', '183.5', 123, 123],
    ['Auf, auf, mein Herz, und du, mein ganzer Sinn', 'Auf, auf, mein Herz, und du, mein ganzer Sinn', '824', '268', 124, 124],
    ['Der Herr ist mein getreuer Hirt (1)', 'Allein Gott in der Höh sei Ehr', '4457', '104.6', 125, 125],
    ['Durch Adams Fall ist ganz verderbt (8)', 'Durch Adams Fall ist ganz verderbt', '7549', '(18.5)', 126, 126],
    ['Dies sind die heilgen zehn Gebot', 'In Gottes Namen fahren wir', '1951', '298', 127, 127],
    ['Alles ist an Gottes Segen', 'Alles ist an Gottes Segen', '3838ff', '263', 128, 128],
    ['Keinen hat Gott verlassen', 'Keinen hat Gott verlassen', '5394', '369', 129, 129],
    ['Meine Seel erhebt den Herren [The German Magnificat]', 'Meine Seel erhebt den Herren [The German Magnificat]', '7372', '324', 130, 130],
    ['Liebster Jesu, wir sind hier', 'Liebster Jesu, wir sind hier', '3498', '373', 131, 131],
    ['Kyrie, Gott Vater in Ewigkeit', 'Kyrie, Gott Vater in Ewigkeit', '8600', '371', 132, 132],
    ['Wir glauben all an einen Gott', 'Wir glauben all an einen Gott', '7971', '437', 133, 133],
    ['Du, o schönes Weltgebäude', 'Du geballtes Weltgebäude', '6773', '301', 137, 134],
    ['Gott der Vater wohn uns bei', 'Gott der Vater wohn uns bei', '8507', '317', 134, 135],
    ['Herr, Jesu Christ, dich zu uns wend', 'Herr, Jesu Christ, dich zu uns wend', '625', '332', 136, 136],
    ['Wer Gott vertraut, hat wohl gebaut', 'Wer Gott vertraut, hat wohl gebaut', '8207', '433', 135, 137],
    ['Jesu, meine Freude (5)', 'Jesu, meine Freude', '8032', '64.8', 138, 138],
    ['Fröhlich soll mein Herze springen (15)', 'Warum sollt ich mich denn grämen', '6461', '248.33', 139, 139],
    ['In allen meinen Taten', 'In allen meinen Taten', '2276', '367', 140, 140],
    ['Seelenbräutigam, Jesu, Gottes Lamm', 'Seelenbräutigam, Jesu, Gottes Lamm', '3255', '409', 141, 141],
    ['Schwing dich auf zu deinem Gott (2)', 'Eine Hoffnung stehe feste', '4870', '40.6', 142, 142],
    ['In dulci jubilo', 'In dulci jubilo', '4947', '368', 143, 143],
    ['Herr, wie du willst, so schicks mit mir', 'Aus tiefer Not schrei ich zu dir (melody #2)', '4438', '339', 144, 144],
    ['Warum betrübst du dich, mein Herz', 'Warum betrübst du dich, mein Herz', '1689', '420', 145, 145],
    ['Wer nur den lieben Gott lässt walten', 'Wer nur den lieben Gott lässt walten', '2778', '434', 146, 146],
    ['Wenn ich in Angst und Not', 'Wenn ich in Angst und Not', '4233', '427', 147, 147],
    ['Uns ist ein Kindlein heut geborn', 'Danket dem Herrn heut und allzeit', '439', '414', 148, 148],
    ['Nicht so traurig, nicht so sehr', 'Nicht so traurig, nicht so sehr', '3355', '384', 149, 149],
    ['Welt, ade! Ich bin dein müde (1)', 'Welt, ade! Ich bin dein müde', '6531', '27.6', 150, 150],
    ['Meinen Jesum lass ich nicht', 'Jesus ist mein Aufenthalt', '3448a', '379', 151, 151],
    ['Meinen Jesum lass ich nicht (6)', 'Meinen Jesum lass ich nicht', '3449', '154.8', 152, 152],
    ['Alle Menschen müssen sterben', 'Alle Menschen müssen sterben', '6778', '262', 153, 153],
    ['Der du bist drei in Einigkeit', 'Der du bist drei in Einigkeit', '335', '293', 154, 154],
    ['Hilf, Herr Jesu, lass gelingen', 'Hilf, Herr Jesu, lass gelingen (melody #1)', '3687', '344', 155, 155],
    ['Ach Gott, wie manches Herzeleid (18)', 'Herr Jesu Christ, meins Lebens Licht (melody #2)', '533a', '3.6', 156, 156],
    ['Wo Gott zum Haus nicht gibt sein Gunst', 'Wo Gott zum Haus nicht gibt sein Gunst', '305', '438', 157, 157],
    ['Der Tag, der ist so freudenreich', 'Der Tag, der ist so freudenreich', '7869f', '294', 158, 158],
    ['Als der gütige Gott', 'Als der gütige Gott', '1646', '264', 159, 159],
    ['Gelobet seist du, Jesu Christ (7)', 'Gelobet seist du, Jesu Christ', '1947', '64.2', 160, 160],
    ['Ihr Gestirn, ihr hohlen Lüfte', 'Ihr Gestirn, ihr hohlen Lüfte', '3703', '366', 161, 161],
    ['Das alte Jahr vergangen ist', 'Das alte Jahr vergangen ist', '381c', '288', 162, 162],
    ['Vor Freuden lasst uns springen', 'Vor Freuden lasst uns springen', '2339', '313', 163, 163],
    ['Herr Gott, dich loben alle wir', 'Herr Gott, dich loben alle wir', '368', '326', 167, 164],
    ['O Lamm Gottes, unschuldig', 'O Lamm Gottes, unschuldig', '4361', '401', 165, 165],
    ['Es stehn vor Gottes Throne', 'Es stehn vor Gottes Throne', '4296', '309', 166, 166],
    ['Du großer Schmerzensmann', 'Du großer Schmerzensmann', '5159', '300', 164, 167],
    ['Heut ist, o Mensch, ein großer Trauertag', 'Heut ist, o Mensch, ein großer Trauertag', '8569a', '341', 168, 168],
    ['Jesu, der du selbsten wohl', 'Jesu, der du selbsten wohl', '6335', '355', 169, 169],
    ['Nun komm, der Heiden Heiland (8)', 'Nun komm, der Heiden Heiland', '1174', '62.6', 170, 170],
    ['Schaut, ihr Sünder', 'Heut ist, o Mensch, ein großer Trauertag', '8569', '408', 171, 171],
    ['Sei gegrüßet, Jesu gütig', 'Sei gegrüßet, Jesu gütig', '3889', '410', 172, 172],
    ['O Herzensangst, o Bangigkeit', 'O Herzensangst, o Bangigkeit', '1003', '400', 173, 173],
    ['Jesus Christus, unser Heiland, der den Tod überwand', 'Jesus Christus, unser Heiland, der den Tod überwand', '1978', '364', 174, 174],
    ['Jesus, meine Zuversicht', 'Jesus, meine Zuversicht', '3432', '365', 175, 175],
    ['Erstanden ist der heilge Christ', 'Erstanden ist der heilge Christ', '1746', '306', 176, 176],
    ['Ach bleib bei uns, Herr Jesu Christ', 'Danket dem Herrn, heut und allzeit', '439', '253', 177, 177],
    ['Das neugeborne Kindelein (4)', 'Das neugeborne Kindelein', '491', '(122.6)', 178, 178],
    ['Wachet auf, ruft uns die Stimme (3)', 'Wachet auf, ruft uns die Stimme', '8405', '140.7', 179, 179],
    ['Als Jesu Christus in der Nacht', 'Als Jesu Christus in der Nacht', '258', '265', 180, 180],
    ['Gott hat das Evangelium', 'Gott hat das Evangelium', '1788', '319', 181, 181],
    ['Wär Gott nicht mit uns diese Zeit (3)', 'Wär Gott nicht mit uns diese Zeit', '4434', '14.5', 182, 182],
    ['Nun freut euch, lieben Christen gmein', 'Nun freut euch, lieben Christen gmein (melody #1)', '4427', '388', 183, 183],
    ['Christ lag in Todesbanden (7)', 'Christ lag in Todesbanden', '7012a', '4.8', 184, 184],
    ['Nun freut euch, Gottes Kinder all', 'Ihr lieben Christen, freut euch nun', '364', '387', 185, 185],
    ['Ach Gott, erhör mein Seufzen und Wehklagen', 'Ach Gott, erhör mein Seufzen und Wehklagen', '1831a', '254', 186, 186],
    ['Komm, Gott Schöpfer, heiliger Geist', 'Komm, Gott Schöpfer, heiliger Geist', '295', '370', 187, 187],
    ['Ich dank dir schon deinen Sohn', 'Ach Herre Gott, mich treibt die Not', '247', '349', 188, 188],
    ['Herr Jesu Christ, wahr Mensch und Gott', 'Herr Jesu Christ, wahr Mensch und Gott', '423', '336', 189, 189],
    ['Herr, nun lass in Friede', 'Herr, nun lass in Friede', '3302', '337', 190, 190],
    ['Von Gott will ich nicht lassen (9)', 'Von Gott will ich nicht lassen', '5264b', '73.5', 191, 191],
    ['Gottlob, es geht nunmehr zum Ende', 'Gottlob, es geht nunmehr zum Ende', '2855', '321', 192, 192],
    ['Was bist du doch, o Seele so betrübet', 'Was bist du doch, o Seele so betrübet', '1837', '424', 193, 193],
    ['Liebster Immanuel, Herzog der Frommen (6)', 'Liebster Immanuel, Herzog der Frommen', '4932c', '123.6', 194, 194],
    ['Wie schön leuchtet der Morgenstern (6)', 'Wie schön leuchtet der Morgenstern', '8359', '(36.4)', 195, 195],
    ['Da der Herr Christ zu Tische saß', 'Da der Herr Christ zu Tische saß', '1560', '285', 196, 196],
    ['Christ ist erstanden', 'Christ ist erstanden', '8584', '276', 197, 197],
    ['Christus, der uns selig macht', 'Christus, der uns selig macht', '6285', '283', 198, 198],
    ['Hilf, Gott, dass mirs gelinge', 'Hilf, Gott, dass mirs gelinge', '4329', '343', 199, 199],
    ['Christus ist erstanden, hat überwunden', 'Christus ist erstanden, hat überwunden', '6240c', '284', 200, 200],
    ['O Mensch, bewein dein Sünde groß', 'Es sind doch selig alle, die im rechten Glauben wandeln', '8303', '402', 201, 201],
    ['O wir armen Sünder!', 'O wie armen Sünder!', '8187', '407', 202, 202],
    ['O Mensch, schau Jesum Christum an', 'O Mensch, schau Jesum Christum an', '3994', '403', 203, 203],
    ['Wer weiss, wie nahe mir mein Ende (1)', 'Wer nur den lieben Gott lässt walten', '2778', '166.6', 204, 204],
    ['Herr Gott, dich loben wir [German Te Deum]', 'Herr Gott, dich loben wir [The German Te Deum] [German Te Deum]', '8652', '328', 205, 205],
    ['So gibst du nun, mein Jesu, gute Nacht!', 'So gibst du nun, mein Jesu, gute Nacht!', '849', '412', 206, 206],
    ['Des heilgen Geistes reiche Gnad', 'Des heilgen Geistes reiche Gnad', '3706', '295', 207, 207],
    ['Als vierzig Tag nach Ostern warn', 'Als vierzig Tag nach Ostern warn', '1743', '266', 208, 208],
    ['Dir, dir, Jehova, will ich singen', 'Dir, dir, Jehova, will ich singen', None, '299', 209, 209],
    ['Christe, du Beistand', 'Christe, du Beistand', '993', '275', 210, 210],
    ['Weltlich Ehr und zeitlich Gut', 'Weltlich Ehr und zeitlich Gut', '4972', '426', 211, 211],
    ['Herr, ich denk an jene Zeit', 'Lob sei dir, gütiger Gott', '4840', '329', 212, 212],
    ['O wie selig seid ihr doch, ihr Frommen', 'O wie selig seid ihr doch, ihr Frommen', '1583', '405', 213, 213],
    ['Mitten wir im Leben sind', 'Mitten wir im Leben sind', '8502', '383', 214, 214],
    ['Verleih uns Frieden gnädiglich', 'Verleih uns Frieden gnädiglich', '1945', '126.6', 215, 215],
    ['Es ist genug (5)', 'Es ist genug', '7173', '60.5', 216, 216],
    ['Ach Gott, wie manches Herzeleid (16,17,18)', 'Herr Jesu Christ, meins Lebens Licht (melody #2)', '533a', '153.9', 217, 217],
    ['Lass, o Herr, dein Ohr sich neigen', 'Lass, o Herr, dein Ohr sich neigen', '6863', '372', 218, 218],
    ['O wie selig seid ihr doch, ihr Frommen', 'Ach, wie groß ist Gottes Güt und Wohltat', '1581', '406', 219, 219],
    ['Sollt ich meinem Gott nicht singen', 'Lasset uns den Herren preisen', '7886', '413', 220, 220],
    ['Herr, straf mich nicht in deinem Zorn (paraph. of Ps.38)', 'Herr, straf mich nicht in deinem Zorn', '4606a', '338', 221, 221],
    ['Nun preiset alle Gottes Barmherzigkeit', 'Nun prieset alle Gottes Barmherzigkeit', '4089', '391', 222, 222],
    ['Ich dank dir Gott für all Wohltat', 'Ich dank dir Gott für all Wohltat', '8090ab', '346', 223, 223],
    ['Das walt Gott Vater und Gott Sohn', 'Das walt Gott Vater und Gott', '673', '290', 224, 224],
    ['Gott, der du selber bist das Licht', 'Gott, der du selber bist das Licht', '5814', '316', 225, 225],
    ['Herr Jesu Christ, du hast bereitt', 'Herr Jesu Christ, du hast bereitt', '4711', '333', 226, 226],
    ['Lobet den Herren, denn er ist sehr freundlich', 'Lobet den Herren, denn er ist sehr freundlich', '975', '374', 227, 227],
    ['Danket dem Herren', 'Danket dem Herren', '12', '286', 228, 228],
    ['Ich danke dir, o Gott in deinem Throne', 'Mein Hüter und mein Hirt ist Gott der Herre', '3199', '350', 229, 229],
    ['Christ, der du bist der helle Tag', 'Christ, der du bist der helle Tag', '384', '273', 230, 230],
    ['Die Nacht ist kommen', 'Die Nacht ist kommen', '5001', '296', 231, 231],
    ['Die Sinn hat sich mit ihrem Glanz', 'O höchster Gott, o unser lieber Herre', '923', '297', 232, 232],
    ['Jesu, meiner Seelen Wonne (2)', 'Werde munter mein Gemüte', '6551', '154.3', 233, 233],
    ['Gott lebet noch', 'Gott lebet noch', '7951', '320', 234, 234],
    ['Heilig, heilig [German Sanctus]', 'Heilig, heilig', '8633', '325', 235, 235],
    ['Herr Jesu Christ, meins Lebens Licht (for B236)', 'Herr Jesu Christ, meins Lebens Licht (melody #1)', '314', '335', 236, 236],
    ['Was betrübst du dich, mein Herz', 'Was betrübst du dich, mein Herz', '6830', '423', 237, 237],
    ['Es wird schier der letzte Tag herkommen', 'Es wird schier der letzte Tag herkommen', '1423', '310', 238, 238],
    ['Den Vater dort oben', 'Den Vater dort oben', '4795', '292', 239, 239],
    ['Nun sich der Tag geendet hat', 'Nun sich der Tag geendet hat', '212', '396', 240, 240],
    ['Was willst du dich, o meine Seele, kränken', 'Was willst du dich, o meine Seele, kränken', '7844', '425', 241, 241],
    ['Wie bist du, Seele, in mir so gar betrübt', 'Wie bist du, Seele, in mir so gar betrübt', '4092', '435', 242, 242],
    ['Jesu, du mein liebstes Leben', 'Jesu, du mein liebstes Leben', '7891', '356', 243, 243],
    ['Jesu, Jesu, du bist mein', 'Jesu, Jesu, du bist mein', '6446', '357', 244, 244],
    ['Christe, der du bist Tag und Licht', 'Christe, der du bist Tag und Licht', '343', '274', 245, 245],
    ['Singt dem Herrn ein neues Lied', 'Singt dem Herrn ein neues Lied', '6424', '411', 246, 246],
    ['Wenn wir in höchsten Nöten sein', 'Wenn wir in höchsten Nöten sein', '394', '432', 247, 247],
    ['Sei Lob und Ehr dem höchsten Gut (4)', 'Es ist das Heil uns kommen her', '4430', '117.4 =117.9', 248, 248],
    ['Allein Gott in der Höh sei Ehr', 'Allein Gott in der Höh sei Ehr', '4457', '260', 249, 249],
    ['Ein feste Burg ist unser Gott', 'Ein feste Burg ist unser Gott', '7377', '303', 250, 250],
    ['Ich bin ja, Herr, in deiner Macht', 'Ich bin ja, Herr, in deiner Macht', '5869', '345', 251, 251],
    ['Jesu, nun sei gepreiset', 'Jesu, nun sei gepreiset', '8477a', '362', 252, 252],
    ['O Gottes Sohn, Herr Jesu Christ (8)', 'Ach Gott, vom Himmel sieh darein', '4431', '77.6', 253, 253],
    ['Treuer Gott, ich muss dir klagen (12)', 'Freu dich sehr, o meine Seele', '6543', '25.6', 254, 254],
    ['Was frag ich nach der Welt (1)', 'O Gott, du frommer Gott (melody #3)', '5206b', '64.4', 255, 255],
    ['Treuer Gott, ich muss dir klagen (6)', 'Freu dich sehr, o meine Seele', '6543', '(194.06)', 256, 256],
    ['Wach auf, mein Herz, und singe', 'Nun lasst uns Gott dem Herren', '159', '(194.12)', 257, 257],
    ['Mein Augen schließ ich jetzt', 'Mein Augen schließ ich jetzt', '1067', '378', 258, 258],
    ['Verleih uns Frieden gnädiglich', 'Verleih uns Frieden gnädiglich', '1945', '(42.7)', 259, 259],
    ['Es ist gewisslich an der Zeit', 'Nun freut euch, lieben Christen gmein (melody #2)', '4429a', '307', 260, 260],
    ['Christ lag in Todesbanden', 'Christ lag in Todesbanden', '7012a', '279', 261, 261],
    ['Ach Gott, vom Himmel sieh darein (6)', 'Ach Gott, vom Himmel sieh darein', '4431', '2.6', 262, 262],
    ['Jesu, meine Freude (1,6)', 'Jesu, meine Freude', '8032', '227.1 =227.11', 263, 263],
    ['Jesu, meines Herzens Freud', 'Jesu, meines Herzens Freud', '4797, 4798d', '361', 264, 264],
    ['Was mein will, das gscheh allzeit (1)', 'Was mein Gott will, das gscheh allzeit', '7568', '144.6', 265, 265],
    ['Herr Jesu Christ, ich schrei zu dir (12)', 'Herr Jesu Christ, du höchstes Gut', '4486', '48.7', 266, 266],
    ['Nimm von uns, Herr, du treuer Gott (7)', 'Vater unser im Himmelreich', '3561', '90.5', 267, 267],
    ['Nun lob, mein Seel, den Herren', 'Nun lob, mein Seel, den Herren', '8244', '389', 268, 268],
    ['Jesu, der du meine Seele', 'Jesu, der du meine Seele', '6804', '353', 269, 269],
    ['Herzlich tut mich verlangen (4)', 'Befiehl du deine Wege (melody #1)', '5385a', '161.6', 270, 270],
    ['Gib dich zufrieden und sei stille', 'Gib dich zufrieden und sei stille', '7417a', '315', 271, 271],
    ['Ich dank dir, lieber Herre', 'Ich dank dir, lieber Herre', '5354b', '348', 272, 272],
    ['Ein feste Burg ist unser Gott (4)', 'Ein feste Burg ist unser Gott', '7377', '80.8', 273, 273],
    ['O Ewigkeit, du Donnerwort', 'O Ewigkeit, du Donnerwort', '5820', '397', 274, 274],
    ['O Welt, sieh hier dein Leben', 'O Welt, ich muss dich lassen', '2293b', '393', 275, 275],
    ['Lobt Gott, ihr Christen, allzugleich', 'Kommt her, ihr lieben Schwesterlein', '198', '375', 276, 276],
    ['Herzlich lieb hab ich dich, o Herr', 'Herzlich lieb hab ich dich, o Herr', '8326', '340', 277, 277],
    ['Wie schön leuchtet der Morgenstern', 'Wie schön leuchtet der Morgenstern', '8359', '436', 278, 278],
    ['Ach Gott und Herr (4)', 'Ach Gott und Herr', '2051', '48.3', 279, 279],
    ['Eins ist not, ach Herr, dies Eine', 'Eins ist not, ach Herr, dies Eine', '7127', '304', 280, 280],
    ['Wo soll ich fliehen hin (7)', 'Wo soll ich fliehen hin', '2164', '89.6', 281, 281],
    ['Treuer Gott, ich muss dir klagen', 'Freu dich sehr, o meine Seele', '6543', '(25.6)', 282, 282],
    ['Jesu, meine Freude (4)', 'Jesu, meine Freude', '8032', '227.7', 283, 283],
    ['Herr Jesu Christ, wahr Mensch und Gott (8)', 'Wenn einer schon ein Haus aufbaut', '2570', '127.5', 283, 284],
    ['Wär Gott nicht mit uns diese Zeit', 'Wo Gott der Herr nicht bei uns hält', '4441a', '257', 284, 285],
    ['Befiehl du deine Wege', 'Befiehl du deine Wege (melody #1)', '5385a', '270', 285, 286],
    ['Herr, ich habe missgehandelt', 'Herr, ich habe missgehandelt', '3695', '331', 286, 287],
    ['Gelobet seist du, Jesu Christ', 'Gelobet seist du, Jesu Christ', '1947', '314', 287, 288],
    ['Nun ruhen alle Wälder', 'O Welt, ich muss dich lassen', '2293b', '392', 288, 289],
    ['Es ist das Heil uns kommen her (7,8)', 'Es ist das Heil uns kommen her', '4430', '9.7', 289, 290],
    ['Was frag ich nach der Welt (7,8)', 'O Gott, du frommer Gott (melody #3)', '5206b', '94.8', 290, 291],
    ['Nimm von uns, Herr, du treuer Gott (7)', 'Vater unser im Himmelreich', '3561', '101.7', 291, 292],
    ['Was Gott tut, das ist wohlgetan (6)', 'Was Gott tut, das ist wohlgetan', '5629', '69a.6', 292, 293],
    ['Herr Jesu Christ, du höchstes Gut (8)', 'Herr Jesu Christ, du höchstes Gut', '4486', '113.8', 293, 294],
    ['O Jesu, du mein Bräutigam (for B294)', 'Herr Jesu Christ, meins Lebens Licht (melody #1)', '314', '(335)', 294, 295],
    ['Nun lob, mein Seel, den Herren', 'Nun lob, mein Seel, den Herren', '8244', '390', 295, 296],
    ['Jesu, der du meine Seele (12)', 'Jesu, der du meine Seele', '6804', '78.7', 296, 297],
    ['Freu dich sehr, o meine Seele (9)', 'Freu dich sehr, o meine Seele', '6543', '19.7', 297, 298],
    ['Meinen Jesum lass ich nicht', 'Meinen Jesum lass ich nicht', '3449', '380', 298, 299],
    ['Warum betrübst du dich, mein Herz', 'Warum betrübst du dich, mein Herz', '1689', '421', 299, 300],
    ['Ach, lieben Christen, seid getrost (6)', 'Wo Gott der Herr nicht bei uns hält', '4441a', '114.7', 300, 301],
    ['Hilf, Gott, dass mirs gelinge', 'Hilf, Gott, dass mirs gelinge', '4329', '(343)', 301, 302],
    ['Herr Christ, der einge Gottessohn (5)', 'Herr Christ, der einge Gottessohn', '4297a', '96.6', 302, 303],
    ['Wo soll ich fliehen hin (11)', 'Wo soll ich fliehen hin', '2164', '5.7', 303, 304],
    ['Wie schön leuchtet der Morgenstern (6)', 'Wie schön leuchtet der Morgenstern', '8359', '(36.4)', 304, 305],
    ['O Mensch, bewein dein Sünde groß', 'Es sind doch selig alle, die im rechten Glauben wandeln', '8303', '(402)', 305, 306],
    ['Christus, der uns selig macht', 'Christus, der uns selig macht', '6285', '(283)', 306, 307],
    ['Ach Gott, wie manches Herzeleid', 'Herr Jesu Christ, meins Lebens Licht (melody #2)', '533a', '(3.6)', 307, 308],
    ['Ein Lämmlein geht und trägt die Schuld (for B5)', 'An Wasserflüssen Babylon', '7663', '(267)', 308, 309],
    ['Durch dein Gefängis, Gottes Sohn', 'Machs mit mir, Gott, nach deiner Güt', '2383', '245.22', 309, 310],
    ['Dank sei Gott in der Höhe', 'Jesus Christ, unser Herre', '5391', '287', 310, 311],
    ['O Gott, du frommer Gott', 'O Gott, du frommer Gott (melody #3)', '5206b', '398', 311, 312],
    ['Der Herr ist mein getreuer Hirt (5)', 'Allein Gott in der Höh sei Ehr', '4457', '112.5', 312, 313],
    ['Das alte Jahr vergangen ist', 'Das alte Jahr vergangen ist', '381c', '289', 313, 314],
    ['O Gott, du frommer Gott', 'O Gott, du frommer Gott (melody #2)', '5148', '399', 314, 315],
    ['Christus, der ist mein Leben', 'Christus, der ist mein Leben', '132', '282', 315, 316],
    ['Herr, wie du willst, so schicks mit mir (1)', 'Aus tiefer Not schrei ich zu dir (melody #2)', '4438', '156.6', 316, 317],
    ['Herr, wie du willst, so schicks mit mir', 'Aus tiefer Not schrei ich zu dir (melody #2)', '4438', '(339)', 317, 318],
    ['Heilig, heilig [German Sanctus]', 'Heilig, heilig', '8633', '(325)', 318, 319],
    ['Gott sei uns gnädig und barmherzig', 'Meine Seel erhebt den Herren [The German Magnificat]', '7372', '323', 319, 320],
    ['Wir Christenleut habn jetzund Freud (3)', 'Wir Christenleut habn jetzund Freud', '2072', '40.3', 320, 321],
    ['Wenn mein Stündlein vorhanden ist', 'Wenn mein Stündlein vorhanden ist', '4482ab', '428', 321, 322],
    ['Wie schön leuchtet der Morgenstern (4)', 'Wie schön leuchtet der Morgenstern', '8359', '172.6', 322, 323],
    ['Jesu, meine Freude (2)', 'Jesu, meine Freude', '8032', '81.7', 323, 324],
    ['Mit Fried und Freud ich fahr dahin (4)', 'Mit Fried und Freud ich fahr dahin', '3986', '83.5', 324, 325],
    ['Der Herr ist mein getreuer Hirt', 'Allein Gott in der Höh sei Ehr', '4457', '(104.6)', 325, 326],
    ['Jesu, nun sei gepreiset (2)', 'Jesu, nun sei gepreiset', '8477a', '190.7', 326, 327],
    ['Liebster Jesu, wir sind hier', 'Liebster Jesu, wir sind hier', '3498', '(373)', 327, 328],
    ['Sei Lob und Ehr dem höchsten Gut', 'Es ist das Heil uns kommen her', '4430', '251', 328, 329],
    ['Nun danket alle Gott', 'Nun danket alle Gott', '5142', '252', 329, 330],
    ['Wo soll ich fliehen hin (9)', 'Wo soll ich fliehen hin', '2164', '136.6', 330, 331],
    ['Von Gott will ich nicht lassen', 'Von Gott will ich nicht lassen', '5264b', '418', 331, 332],
    ['Es woll uns Gott genädig sein (3)', 'Es woll uns Gott genädig sein', '7247', '69.6', 332, 333],
    ['Vor deinen Thron tret ich hiermit', 'Herr Gott, dich loben alle wir', '368', '327', 333, 334],
    ['Es ist das Heil uns kommen her (12)', 'Es ist das Heil uns kommen her', '4430', '155.5', 334, 335],
    ['Wo Gott der Herr nicht bei uns hält', 'Wo Gott der Herr nicht bei uns hält', '4441a', '258', 335, 336],
    ['O Gott, du frommer Gott (1)', 'O Gott, du frommer Gott (melody #2)', '5148', '24.6', 336, 337],
    ['Auf, mein Herz, des Herren Tag (1)', 'Jesus, meine Zuversicht', '3432', '145a', 337, 338],
    ['Ich armer Mensch, ich armer Sünder (1)', 'Wer nur den lieben Gott lässt walten', '2778', '179.6', 338, 339],
    ['Befiehl du deine Wege', 'Befiehl du deine Wege (melody #2)', '5393', '272', 339, 340],
    ['Ich dank dir, lieber Herre (4)', 'Ich dank dir, lieber Herre', '5354b', '37.6', 340, 341],
    ['Lobt Gott, ihr Christen, allzugleich', 'Kommt her, ihr lieben Schwesterlein', '198', '376', 341, 342],
    ['Du Du Lebensfürst, Herr Jesu Christ (4)', 'Ermuntre dich, mein schwacher Geist', '5741', '11.6', 342, 343],
    ['Wir singen dir, Immanuel (2)', 'Vom Himmel hoch, da komm ich her', '346', '248.23', 343, 344],
    ['Wie soll ich dich empfangen (1)', 'Befiehl du deine Wege (melody #1)', '5385a', '248.05', 344, 345],
    ['Meines Lebens letzte Zeit', 'Meines Lebens letzte Zeit', '6380', '381', 345, 346],
    ['Was Gott tut, das ist wohlgetan', 'Was Gott tut, das ist wohlgetan', '5629', '250', 346, 347],
    ['Meinen Jesum lass ich nicht (5)', 'Meinen Jesum lass ich nicht', '3449', '70.11', 347, 348],
    ['Barmherzger Vater, höchster Gott', 'Was mein Gott will, das gscheh allzeit', '7568', '(103.6)', 348, 349],
    ['Jesu, meiner Seelen Wonne', 'Werde munter mein Gemüte', '6551', '360', 349, 350],
    ['Wenn mein Stündlein vorhanden ist', 'Wenn mein Stündlein vorhanden ist', '4482ab', '430', 350, 351],
    ['Es woll uns Gott genädig sein', 'Es woll uns Gott genädig sein', '7247', '312', 351, 352],
    ['Der Herr ist mein getreuer Hirt', 'Allein Gott in der Höh sei Ehr', '4457', '(112.5)', 352, 353],
    ['Sei Lob und Ehr dem höchsten Gut', 'Es ist das Heil uns kommen her', '4430', '(117.4 =117.9)', 353, 354],
    ['In allen meinen Taten (15)', 'O Welt, ich muss dich lassen', '2293b', '44.7', 354, 355],
    ['Jesu, meine Freude', 'Jesu, meine Freude', '8032', '358', 355, 356],
    ['Warum sollt ich mich denn grämen', 'Warum sollt ich mich denn grämen', '6461', '422', 356, 357],
    ['Meine Seel erhebt den Herren [The German Magnificat]', 'Meine Seel erhebt den Herren [The German Magnificat]', None, '10.7', 357, 358],
    ['Allein zu dir, Herr Jesu Christ', 'Allein zu dir, Herr Jesu Christ', '7292b', '261', 358, 359],
    ['Lasst Furcht und Pein (4)', 'Wir Christenleut habn jetzund Freud', '2072', '248.35', 359, 360],
    ['Ermuntre dich, mein schwacher Geist (9)', 'Ermuntre dich, mein schwacher Geist', '5741', '(248.12)', 360, 361],
    ['Ich steh an deiner Krippen hier (1)', 'Nun freut euch, lieben Christen gmein (melody #2)', '4429a', '248.59', 361, 362],
    ['O Welt, sieh hier dein Leben', 'O Welt, ich muss dich lassen', '2293b', '395', 362, 363],
    ['Von Gott will ich nicht lassen', 'Von Gott will ich nicht lassen', '5264b', '417', 363, 364],
    ['Jesu, meiner Seelen Wonne', 'Werde munter mein Gemüte', '6551', '359', 364, 365],
    ['O Welt, sieh hier dein Leben', 'O Welt, ich muss dich lassen', '2293b', '394', 365, 366],
    ['Befiehl du deine Wege', 'Befiehl du deine Wege (melody #1)', '5385a', '271', 366, 367],
    ['Hilf, Herr Jesu, lass gelingen (15)', 'Hilf, Herr Jesu, lass gelingen (melody #2)', None, '248.42', 367, 368],
    ['Jesu, der du meine Seele', 'Jesu, der du meine Seele', '6804', '354', 368, 369],
    ['Gott Vater, sende deinen Geist (2)', 'Kommt her zu mir, spricht Gottes Sohn', '2496c', '74.8', 369, 370],
    ['Christ lag in Todesbanden', 'Christ lag in Todesbanden', '7012a', '278', 370, 371],

]

col_dict = {
    "text": 0,
    "tune": 1,
    "Zahn": 2,
    "BWV": 3,
    "CPE": 4,
    "Riemenschneider": 5
}

score_titles = [
    None,
    "Aus meines Herzens Grunde",
    "Ich dank' dir, lieber Herre",
    "Ach Gott, vom Himmel sieh' darein",
    "Es ist das Heil uns kommen her",
    "An Wasserflüssen Babylon",
    "Nun lob', mein' Seel', den Herren",
    "Christus, der ist mein Leben",
    "Freuet euch, ihr Christen",
    "Ermuntre dich, mein schwacher Geist",
    "Aus tiefer Not schrei' ich zu dir",
    "Jesu, nun sei gepreiset",
    "Puer natus in Bethlehem",
    "Allein zu dir, Herr Jesu Christ",
    "O Herre Gott, dein göttlich Wort",
    "Christ lag in Todesbanden",
    "Es woll' uns Gott genädig sein",
    "Erschienen ist der herrliche Tag",
    "Gottes Sohn ist kommen",
    "Ich hab' mein' Sach' Gott heimgestellt",
    "Ein' feste Burg ist unser Gott",
    "Herzlich tut mich verlangen",
    "Schmücke dich, o liebe Seele",
    "Zeuch ein zu deinen Toren",
    "Valet will ich dir geben",
    "Wo soll ich fliehen hin",
    "O Ewigkeit, du Donnerwort",
    "Es spricht der Unweisen Mund wohl",
    "Nun komm, der Heiden Heiland",
    "Freu' dich sehr, o meine Seele",
    "Jesus Christus, unser Heiland",
    "Ach lieben Christen, seid getrost",
    "Nun danket alle Gott",
    "Erbarm' dich mein, o Herre Gott",
    "Gott des Himmels und der Erden",
    "Herr, ich habe missgehandelt",
    "Nun bitten wir den heiligen Geist",
    "Jesu, der du meine Seele",
    "Straf' mich nicht in deinem Zorn",
    "Ach, was soll ich Sünder machen",
    "Ach Gott und Herr",
    "Was mein Gott will, das gescheh' allzeit",
    "Du Friedensfürst, Herr Jesu Christ",
    "Liebster Gott, wann werd' ich sterben",
    "Mach's mit mir, Gott, nach deiner Güt'",
    "Vom Himmel hoch da komm' ich her",
    "Kommt her zu mir, spricht Gottes Sohn",
    "Vater unser im Himmelreich",
    "Ach wie nichtig, ach wie flüchtig",
    "Mit Fried' und Freud' fahr' ich dahin",
    "In allen meinen Taten",
    "Wenn mein Stündlein vorhanden ist",
    "Das neugeborne Kindelein",
    "Gelobet seist du Jesu Christ",
    "Lobt Gott, ihr Christen, allzugleich",
    "Christum wir sollen loben schon",
    "Herzlich lieb hab' ich dich, o Herr",
    "Wir Christenleut'",
    "Herzliebster Jesu, was hast du verbrochen",
    "Jesu Leiden, Pein und Tod",
    "O Traurigkeit, o Herzeleid",
    "Ich freue mich in dir",
    "Nun ruhen alle Wälder",
    "Freu' dich sehr, o meine Seele",
    "Was Gott tut, das ist wohlgetan",
    "Christ, unser Herr, zum Jordan kam",
    "Wer nur den lieben Gott lässt walten",
    "Freu' dich sehr, o meine Seele",
    "Wenn wir in höchsten Nöten sein",
    "Komm, heiliger Geist, Herre Gott",
    "Gott sei gelobet und gebenedeiet",
    "Ich ruf' zu dir, Herr Jesu Christ",
    "Erhalt' uns, Herr, bei deinem Wort",
    "Herr Jesu Christ, du höchstes Gut",
    "O Haupt voll Blut und Wunden",
    "Das walt' mein Gott",
    "Freu' dich sehr, o meine Seele",
    "In dich hab' ich gehoffet, Herr",
    "Herzliebster Jesu, was hast du verbrochen",
    "Heut' triumphiret Gottes Sohn",
    "Christus, der uns selig macht",
    "O großer Gott von Macht",
    "Jesu Leiden, Pein und Tod",
    "Nun bitten wir den heiligen Geist",
    "O Gott, du frommer Gott",
    "Wie schön leuchtet der Morgenstern",
    "Du, o schönes Weltgebäude",
    "O Haupt voll Blut und Wunden",
    "Helft mir Gott's Güte preisen",
    "O Haupt voll Blut und Wunden",
    "Hast du denn, Jesu, dein Angesicht",
    "Verleih' uns Frieden gnädiglich",
    "O Jesu Christ, du höchstes Gut",
    "Wach' auf, mein Herz, und singe",
    "Warum betrübst du dich, mein Herz",
    "Werde munter, mein Gemüte",
    "Jesu, meine Freude",
    "Nun bitten wir den heiligen Geist",
    "O Haupt voll Blut und Wunden",
    "Helft mir Gott's Güte preisen",
    "Ich ruf' zu dir, Herr Jesu Christ",
    "Herr Christ, der ein'ge Gott'ssohn",
    "Ermuntre dich, mein schwacher Geist",
    "Nun ruhen alle Wälder",
    "Wer nur den lieben Gott lässt walten",
    "Herzliebster Jesu, was hast du verbrochen",
    "Jesu Leiden, Pein und Tod",
    "Herzlich lieb hab' ich dich, o Herr",
    "Valet will ich dir geben",
    "Singen wir aus Herzens Grund",
    "Vater unser im Himmelreich",
    "Herzliebster Jesu, was hast du verbrochen",
    "Wer nur den lieben Gott lässt walten",
    "Christus, der uns selig macht",
    "Von Gott will ich nicht lassen",
    "Was mein Gott will, das gescheh' allzeit",
    "Nun lob', mein' Seel', den Herren",
    "Nun ruhen alle Wälder",
    "In dich hab' ich gehoffet, Herr",
    "Christ, unser Herr, zum Jordan kam",
    "Was mein Gott will, das gescheh' allzeit",
    "Werde munter, mein Gemüte",
    "Ist Gott mein Schild und Helfersmann",
    "Helft mir Gott's Güte preisen",
    "Auf, auf, mein Herz, und du mein ganzer",
    "Allein Gott in der Höh' sei Ehr'",
    "Durch Adams Fall ist ganz verderbt",
    "Dies sind die heil'gen zehn Gebot'",
    "Alles ist an Gottes Segen",
    "Keinen hat Gott verlassen",
    "Meine Seele erhebet den Herrn",
    "Liebster Jesu, wir sind hier",
    "Kyrie, Gott Vater in Ewigkeit",
    "Wir glauben all' an einen Gott",
    "Gott der Vater wohn' uns bei",
    "Wer Gott vertraut, hat wohl gebaut",
    "Herr Jesu Christ, dich zu uns wend'",
    "Du, o schönes Weltgebäude",
    "Jesu, meine Freude",
    "Warum sollt' ich mich denn grämen",
    "In allen meinen Taten",
    "Seelen-Bräutigam",
    "Schwing' dich auf zu deinem Gott",
    "In dulci jubilo",
    "Wer in dem Schutz des Höchsten ist",
    "Warum betrübst du dich, mein Herz",
    "Wer nur den lieben Gott lässt walten",
    "Wenn ich in Angst und Not",
    "Uns ist ein Kindlein heut' gebor'n",
    "Nicht so traurig, nicht so sehr",
    "Welt, ade! ich bin dein müde",
    "Meinen Jesum lass' ich nicht, Jesus",
    "Meinen Jesum lass' ich nicht, weil",
    "Alle Menschen müssen sterben",
    "Der du bist drei in Einigkeit",
    "Hilf, Herr Jesu, lass gelingen",
    "Ach Gott, wie manches Herzeleid",
    "Wo Gott zum Haus nicht gibt sein' Gunst",
    "Der Tag, der ist so freudenreich",
    "Als der gütige Gott",
    "Gelobet seist du Jesu Christ",
    "Ihr Gestirn', ihr hohlen Lüfte",
    "Das alte Jahr vergangen ist",
    "Für Freuden lasst uns springen",
    "Du großer Schmerzensmann",
    "O Lamm Gottes, unschuldig",
    "Es stehn vor Gottes Throne",
    "Herr Gott, dich loben alle wir",
    "Heut' ist, o Mensch, ein großer",
    "Jesu, der du selbsten wohl",
    "Nun komm, der Heiden Heiland",
    "Schaut, ihr Sünder",
    "Sei gegrüßet, Jesu gütig",
    "O Herzensangst",
    "Jesus Christus, unser Heiland",
    "Jesus, meine Zuversicht",
    "Erstanden ist der heil'ge Christ",
    "Ach bleib bei uns, Herr Jesu Christ",
    "Das neugeborne Kindelein",
    "Wachet auf, ruft uns die Stimme",
    "Als Jesus Christus in der Nacht",
    "Gott hat das Evangelium",
    "Wär' Gott nicht mit uns diese Zeit",
    "Nun freut euch, lieben Christen, g'mein",
    "Christ lag in Todesbanden",
    "Nun freut euch, Gottes Kinder all'",
    "Ach Gott, erhör' mein Seufzen",
    "Komm, Gott Schöpfer, heiliger Geist",
    "Ich dank' dir schon durch deinen Sohn",
    "Herr Jesu Christ, wahr'r Mensch und Gott",
    "Herr, nun lass in Friede",
    "Von Gott will ich nicht lassen",
    "Gottlob, es geht nunmehr zu Ende",
    "Was bist du doch, o Seele, so betrübet",
    "Liebster Immanuel, Herzog der Frommen",
    "Wie schön leuchtet der Morgenstern",
    "Da der Herr Christ zu Tische saß",
    "Christ ist erstanden",
    "Christus, der uns selig macht",
    "Hilf, Gott, dass mir's gelinge",
    "Christus ist erstanden, hat überwunden",
    "O Mensch, bewein' dein' Sünde groß",
    "O wir armen Sünder",
    "O Mensch, schau Jesum Christum an",
    "Wer weiß, wie nahe mir",
    "Herr Gott, dich loben wir",
    "So gibst du nun, mein Jesu, gute Nacht",
    "Des heil'gen Geistes reiche Gnad'",
    "Als vierzig Tag' nach Ostern",
    "Dir, dir, Jehova, will ich singen",
    "Christe, du Beistand deiner Kreuzgemeine",
    "Weltlich Ehr' und",
    "Herr, ich denk' an jene Zeit",
    "O wie selig seid ihr doch, ihr Frommen",
    "Mitten wir im Leben sind",
    "Verleih' uns Frieden gnädiglich",
    "Es ist genug, so nimm, Herr",
    "Ach Gott, wie manches Herzeleid",
    "Lass, o Herr, dein Ohr sich neigen",
    "O wie selig seid ihr doch, ihr Frommen",
    "Sollt' ich meinem Gott nicht singen",
    "Herr, straf' mich nicht in deinem Zorn",
    "Nun preiset alle",
    "Ich dank' dir, Gott, für all' Wohltat",
    "Das walt' Gott Vater und Gott Sohn",
    "Gott, der du selber bist das Licht",
    "Herr Jesu Christ, du hast bereit",
    "Lobet den Herren, denn er ist sehr freundlich",
    "Danket dem Herren, denn er ist sehr freundlich",
    "Ich danke dir, o Gott, in deinem Throne",
    "Christ, der du bist der helle Tag",
    "Die Nacht ist kommen",
    "Die Sonn' hat sich mit ihrem Glanz",
    "Werde munter, mein Gemüte",
    "Gott lebet noch",
    "Heilig, heilig",
    "O Jesu, du mein Bräutigam",
    "Was betrübst du dich, mein Herze",
    "Es wird schier der letzte Tag",
    "Den Vater dort oben",
    "Nun sich der Tag geendet hat",
    "Was willst du dich, o meine Seele",
    "Wie bist du, Seele",
    "Jesu, du mein liebstes Leben",
    "Jesu, Jesu, du bist mein",
    "Christe, der du bist Tag und Licht",
    "Singt dem Herrn ein neues Lied",
    "Wenn wir in höchsten Nöten sein",
    "Sei Lob und Ehr' dem höchsten Gut",
    "Allein Gott in der Höh' sei Ehr'",
    "Ein' feste Burg ist unser Gott",
    "Ich bin ja, Herr, in deiner Macht",
    "Jesu, nun sei gepreiset",
    "Ach Gott, vom Himmel sieh' darein",
    "Weg, mein Herz, mit den Gedanken",
    "Was frag' ich nach der Welt",
    "Jesu, deine tiefen Wunden",
    "Nun lasst uns Gott, dem Herren",
    "Mein' Augen schließ' ich jetzt",
    "Verleih' uns Frieden gnädiglich",
    "Es ist gewisslich an der Zeit",
    "Christ lag in Todesbanden",
    "Ach Gott, vom Himmel sieh' darein",
    "Jesu, meine Freude",
    "Jesu, meines Herzens Freud'",
    "Was mein Gott will, das gescheh' allzeit",
    "Herr Jesu Christ, du höchstes Gut",
    "Vater unser im Himmelreich",
    "Nun lob', mein' Seel', den Herren",
    "Jesu, der du meine Seele",
    "Befiehl du deine Wege",
    "Gib dich zufrieden und sei stille",
    "Ich dank' dir, lieber Herre",
    "Ein' feste Burg ist unser Gott",
    "O Ewigkeit, du Donnerwort",
    "O Welt, sieh hier dein Leben",
    "Lobt Gott, ihr Christen, allzugleich",
    "Herzlich lieb hab' ich dich, o Herr",
    "Wie schön leuchtet der Morgenstern",
    "Ach Gott und Herr",
    "Eins ist not! ach Herr, dies Eine",
    "Wo soll ich fliehen hin",
    "Freu' dich sehr, o meine Seele",
    "Jesu, meine Freude",
    "Herr Jesu Christ, wahr'r Mensch und Gott",
    "Wär' Gott nicht mit uns diese Zeit",
    "Befiehl du deine Wege",
    "Herr, ich habe missgehandelt",
    "Gelobet seist du Jesu Christ",
    "Nun ruhen alle Wälder",
    "Es ist das Heil uns kommen her",
    "Was frag' ich nach der Welt",
    "Nimm von uns, Herr, du treuer Gott",
    "Was Gott tut, das ist wohlgetan",
    "Herr Jesu Christ, du höchstes Gut",
    "Herr Jesu Christ, mein's Lebens Licht",
    "Nun lob', mein' Seel', den Herren",
    "Jesu, der du meine Seele",
    "Weg, mein Herz, mit den Gedanken",
    "Meinen Jesum lass' ich nicht",
    "Warum betrübst du dich, mein Herz",
    "Ach lieben Christen, seid getrost",
    "Hilf, Gott, dass mir's gelinge",
    "Herr Christ, der ein'ge Gott'ssohn",
    "Auf meinen lieben Gott",
    "Wie schön leuchtet der Morgenstern",
    "O Mensch, bewein' dein' Sünde groß",
    "Christus, der uns selig macht",
    "Ach Gott, wie manches Herzeleid",
    "Ein Lämmlein geht und trägt die Schuld",
    "Mach's mit mir, Gott, nach deiner Güt'",
    "Dank sei Gott in der Höhe",
    "O Gott, du frommer Gott",
    "Allein Gott in der Höh' sei Ehr'",
    "Das alte Jahr vergangen ist",
    "O Gott, du frommer Gott",
    "Christus, der ist mein Leben",
    "Herr, wie du willst, so schick's mit mir",
    "Herr, wie du willst, so schick's mit mir",
    "Sanctus, Sanctus Dominus Deus Sabaoth",
    "Gott sei uns gnädig und barmherzig",
    "Wir Christenleut'",
    "Wenn mein Stündlein vorhanden ist",
    "Wie schön leuchtet der Morgenstern",
    "Jesu, meine Freude",
    "Mit Fried' und Freud' fahr' ich dahin",
    "Allein Gott in der Höh' sei Ehr'",
    "Jesu, nun sei gepreiset",
    "Liebster Jesu, wir sind hier",
    "Sei Lob und Ehr' dem höchsten Gut",
    "Nun danket alle Gott",
    "Wo soll ich fliehen hin",
    "Von Gott will ich nicht lassen",
    "Es woll' uns Gott genädig sein",
    "Für deinen Thron tret' ich hiermit",
    "Es ist das Heil uns kommen her",
    "Wo Gott der Herr nicht bei uns hält",
    "O Gott, du frommer Gott",
    "Jesus, meine Zuversicht",
    "Wer nur den lieben Gott lässt walten",
    "Befiehl du deine Wege",
    "Ich dank' dir, lieber Herre",
    "Lobt Gott, ihr Christen, allzugleich",
    "Nun lieget alles unter dir",
    "Vom Himmel hoch da komm' ich her",
    "O Haupt voll Blut und Wunden",
    "Meines Lebens letzte Zeit",
    "Was Gott tut, das ist wohlgetan",
    "Meinen Jesum lass' ich nicht",
    "Ich hab' in Gottes Herz und Sinn",
    "Jesu, meiner Seelen Wonne",
    "Wenn mein Stündlein vorhanden ist",
    "Es woll' uns Gott genädig sein",
    "Der Herr ist mein getreuer Hirt",
    "Sei Lob und Ehr' dem höchsten Gut",
    "Nun ruhen alle Wälder",
    "Jesu, meine Freude",
    "Warum sollt' ich mich denn grämen",
    "Meine Seele erhebt den Herren",
    "Allein zu dir, Herr Jesu Christ",
    "Wir Christenleut'",
    "Du Lebensfürst, Herr Jesu Christ",
    "Es ist gewisslich an der Zeit",
    "O Welt, sieh hier dein Leben",
    "Von Gott will ich nicht lassen",
    "Jesu, meiner Seelen Wonne",
    "O Welt, sieh hier dein Leben",
    "Befiehl du deine Wege",
    "Hilf, Herr Jesu, lass gelingen",
    "Jesu, der du meine Seele",
    "Kommt her zu mir, spricht Gottes Sohn",
    "Christ lag in Todesbanden",
]

analysis_titles = [
    None,
    "Aus meines Herzens Grunde",
    "Ich dank dir, lieber Herre",
    "Ach Gott, vom Himmel sieh' darein",
    "Es ist das Heil uns kommen her",
    "An Wasserflüssen Babylon",
    "Christus, der ist mein Leben",
    "Nun lob, mein Seel, den Herren",
    "Freuet euch, ihr Christen alle",
    "Ermuntre dich, mein schwacher Geist",
    "Aus tiefer Not schrei ich zu dir 1",
    "Jesu, nun sei gepreiset",
    "Puer natus in Bethlehem",
    "Allein zu dir, Herr Jesu Christ",
    "O Herre Gott, dein göttlich Wort",
    "Christ lag in Todesbanden",
    "Es woll uns Gott genädig sein",
    "Erschienen ist der herrliche Tag",
    "Menschenkind, merk eben",
    "Ich hab mein Sach Gott heimgestellt",
    "Ein feste Burg ist unser Gott",
    "Herzlich tut mich verlangen",
    "Schmücke dich, o liebe Seele",
    "Helft mir Gotts Güte preisen",
    "Valet will ich dir geben",
    "Wo soll ich fliehen hin",
    "O Ewigkeit, du Donnerwort",
    "Es spricht der Unweisen Mund",
    "Nun komm, der Heiden Heiland",
    "Wie nach einer Wasserquelle",
    "Jesus Christus, unser Heiland, der von uns den Gottes Zorn wandt",
    "Wo Gott der Herr nicht bei uns hält",
    "Nun danket alle Gott",
    "Herr, ich habe mißgehandelt",
    "Erbarm dich mein, o Herre Gott",
    "Gott des Himmels und der Erden",
    "Nun bitten wir den heiligen Geist",
    "Wachet doch, erwacht, ihr Schläfer",
    "Straf' mich nicht in deinem Zorn",
    "Ach, was soll ich Sünder machen",
    "Ach Gott und Herr, wie groß und schwer",
    "Was mein Gott will, das g'scheh allzeit",
    "Du Friedefürst, Herr Jesu Christ",
    "Liebster Gott, wann werd ich sterben",
    "Mach's mit mir, Gott, nach deiner Güt",
    "Kommt her zu mir, spricht Gottes Söhn",
    "Vom Himmel hoch, da komm ich her",
    "Vater unser im Himmelreich",
    "Ach wie nichtig, ach wie flüchtig",
    "Mit Fried und Freud ich fahr dahin",
    "O Welt, ich muß dich lassen",
    "Gelobet seist du, Jesu Christ",
    "Wenn mein Stündlein vorhanden ist",
    "Das neugeborne Kindelein",
    "Lobt Gott, ihr Christen, allzugleich",
    "Wir Christenleut'",
    "Christum wir sollen loben schon",
    "O Traurigkeit",
    "Herzlich lieb hab' ich dich, o Herr",
    "Herzliebster Jesu, was hast du",
    "Ich freue mich in dir",
    "Jesu Leiden, Pein und Tod",
    "Wer nur den lieben Gott laesst walten",
    "O Welt, sieh hier dein Leben",
    "Freu dich sehr, o meine Seele",
    "Was Gott thut, das ist wohlgethan",
    "Christ, unser Herr, zum Jordan kam",
    "Freu dich sehr, o meine Seele",
    "Wenn wir in höchsten Nöten sein",
    "Komm, heiliger Geist. Herre Gott",
    "Gott sei gelobet und gebenedeiet",
    "Ich ruf' zu dir, Herr Jesu Christ",
    "Erhalt uns, Herr, bei deinem Wort",
    "Herr Jesu Christ, du höchstes Gut",
    "O Haupt voll Blut und Wunden",
    "Das walt' mein Gott",
    "Freu' dich sehr, o meine Seele",
    "In dich hab' ich gehoffet, Herr'",
    "Herzliebster Jesu, was hast du",
    "Heut' triumphiret Gottes Sohn",
    "O Haupt voll Blut und Wunden",
    "Christus, der uns selig macht",
    "O großer Gott von Macht",
    "Jesu Leiden, Pein und Tod",
    "Nun bitten wir den heiligen Geist",
    "O Gott, du frommer Gott",
    "Wie schön leuchtet der Morgenstern",
    "Du, o schönes Weltgebäude",
    "helft mir Gott's Güte preisen",
    "O Haupt voll Blut und Wunden",
    "Hast du denn, Jesu, dein Angesight",
    "Verleih' uns Frieden gnädiglich",
    "O Jesu Christ, du höchstes Gut",
    "Wach' auf, mein Herz",
    "Warum betrübst du dich, mein Herz",
    "Werde munter, mein Gemüte",
    "Jesu, meine Freude",
    "Nun bitten wir den heiligen Geist",
    "O Haupt voll Blut and Wunden",
    "Helft mir Gott's Güte preisen",
    "Durch Adams Fall ist ganz verderbt",
    "Herr Christ, der ein'ge Gott's-Sohn",
    "Ermuntre dich, mein schwacher Geist",
    "Nun ruhen alle Wälder",
    "Wer nun den lieben Gott lässt walten",
    "Herzliebster Jesu, was hast du verbrochen",
    "Jesu Leiden, Pein und Tod",
    "Herzlich lieb hab' ich dich, o Herr",
    "Valet will ich dir geben",
    "Singen wir aus Herzens Grund",
    "Vater unser in Himmelreich",
    "Herzliebster Jesu, was hast du verbrochen",
    "Wer nur den lieben Gott lässt walten",
    "Christus, der uns selig macht",
    "Von Gott will ich nicht lassen",
    "das Was mein Gott will",
    "Nun lob', mein' Seel', den Herren",
    "Nun ruhen alle Wälder",
    "In dich hab' ich gehoffet, Herr",
    "Christ, unser Herr, zum Jordan kam",
    "Was mein Gott will, das g'scheh' allzeit",
    "Werde munter, mein Gemüte",
    "Ist Gott mein Schild und Helfersmann",
    "Helft mir Gott's Güte preisen",
    "Auf, auf, mein Herz, und du mein ganzer Sinn",
    "Allein Gott in der Höh' sei Ehr'",
    "Durch Adams Fall ist ganz verderbt",
    "Dies sind die heil'gen zehn Gebot",
    "Alles ist an Gottes Segen",
    "Keinen hat Gott verlassen",
    "Meine Seele erhebet den Herrn",
    "Liebster Jesu, wir sind hier",
    "Kyrie, Gott Vater in Ewegkeit",
    "Wir glauben all' an einem Gott",
    "Du, o schönes Weltgebäude",
    "Gott der Vater wohn' uns bei",
    "Herr Jesu Christ, dich zu uns wend'",
    "Wer Gott vertraut, hat wohl gebaut",
    "Jesu, meine Freude",
    "Warum sollt ich mich denn grämen",
    "In allen meinen Taten",
    "Seelen-Bräutigam",
    "Schwing' dich auf zu deinem Gott",
    "In dulci jubilo",
    "Wer in dem Schutz des Höchsten",
    "Warum betrübst du dich",
    "Wer nur den lieben Gott lässt walten",
    "Wenn ich in Angst und Not",
    "Uns ist ein Kindlein heut' gebor'n",
    "Nicht so traurig, nicht so sehr",
    "Welt, ade! ich bin dein mude",
    "Meinen Jesum laß' ich nicht, Jesus",
    "Meinen Jesum laß' ich nicht, Weil",
    "Alle Menschen müssen sterben",
    "Der du bist drei in Einigkeit",
    "Hilf, Herr Jesu, laß gelingen",
    "Ach Gott, wie manches Herzeleid",
    "Wo Gott zum Haus nicht gibt",
    "Der Tag, der ist so freudenreich",
    "Als der gütige Gott",
    "Gelobet seist du, Jesu Christ",
    "Ihr Gestirn', ihr hohlen Lüfte",
    "Das alte Jahr vergangen ist",
    "Für Freuden laßt uns springen",
    "Herr Gott, dich loben alle wir",
    "O Lamm Gottes, unschuldig",
    "Es stehn vor Gottes Throne",
    "Du großer Schmerzensmann",
    "Heut' ist, o Mensch, ein großer",
    "Jesu, der du gelbsten wohl",
    "Nun komm, der Heiden Heiland",
    "Schaut, ihr Sünder",
    "Sei gegrüßet, Jesu gütig",
    "O Herzensangst",
    "Jesus Christus, unser Heiland, der den Tod",
    "Jesus, meine Zuversicht",
    "Erstanden ist der heil'ge Christ",
    "Ach bleib bei uns, Herr Jesu Christ",
    "Das neugeborne Kindelein",
    "Wachtet auf, ruft uns die Stimme",
    "Als Jesus Christus in der Nacht",
    "Gott hat das Evangelium",
    "Wär' Gott night mitt uns diese Zeit",
    "Nun freut euch, lieben Christen, g'mein",
    "Christ lag in Todesbanden",
    "Nun fret euch, Gottes Kinder all'",
    "Ach Gott, erhör mein Seufzen",
    "Komm, Gott Schöpfer, heiliger Geist",
    "Ich dank' dir schon durch deinen Sohn",
    "Herr Jesu Christ, wahr'r Mensch und Gott",
    "Herr, nun laß in Frieden",
    "Von Gott will ich nicht lassen",
    "Gottlob, es geht nunmehr zu Ende",
    "Was bist du doch, o Seele, so betrübet",
    "Liebster Immanuel, Herzog der Frommen",
    "Wie schön leuchtet der Morgenstern",
    "Da der Herr Christ zu Tische saß",
    "Christ ist erstanden/Wär er nicht erstanden/Alleluja",
    "Christus, der uns selig macht",
    "Hilf, Gott, daß mir's gelinge",
    "Christus ist erstanden, hat überwunden",
    "O Mensch, bewein' dein' Sünde groß",
    "O wir armen Sünder",
    "O Mensch, schau Jesum Christum an",
    "Wir weiß, wie nahe mir",
    "Herr Gott, dich loben wir [Te Deum]",
    "So gibst du nun, mein Jesu, gute Nacht",
    "Das heil'gen Geistes reiche Gnad'",
    "Als vierzig Tag' nach Ostern",
    "Dir, dir, Jehovah, will ich singen",
    "Christe, du Beistand deiner Kruzgemeine",
    "Weltlich Ehr' und zeitlich Gut",
    "Herr, ich denk' an jene Zeit",
    "O wie selig seid ihr doch, ihr Frommen",
    "Mitten wir im Leben sind",
    "Verleih' uns Frieden gnädlich",
    "Es ist genug; so nimm, Herr",
    "Ach Gott, wie manches Herzeleid",
    "Laß, o Herr, dein Ohr sich neigen",
    "O wie selig seid ihr doch, ihr Frommen",
    "Sollt' ich meinem Gott nicht singen",
    "Herr, straf mich nicht in deinem Zorn",
    "Nun priset alle",
    "Ich dank dir, Gott, für all' Wohltat",
    "???",
    "Gott, der du selber bist das Licht",
    "Herr Jesu Christ, du hast bereit",
    "Lobet den Herren, denn er ist sehr freundlich",
    "Danket dem Herren, denn er ist sehr freundlich",
    "Ich danke dir, o Gott, in deinem Throne",
    "Christ, der du  bist der helle Tag",
    "Die Nacht is kommen",
    "Die Sonn' hat sich mit ihrem Glanz",
    "Werde munter, mein Gemüte",
    "Gott lebet noch",
    "Heilig, heilig",
    "O Jesu, du mein Bräutigan",
    "Was betrübst du dich, mein Herze",
    "Es wird schier der letzte Tag",
    "Den Vater dort oben",
    "Nun sich der Tag geendet hat",
    "Was willst du dich, o meine Seele",
    "Wie bist du, Seele",
    "Jesu, du mein liebstes Leben",
    "Jesu, Jesu, du bist mein",
    "Christe, der du bist Tag und Licht",
    "Singt dem Herrn ein neues Lied",
    "Wenn wir in höchsten Nöten sein",
    "Sei Lob und Ehr den höchsten Gut",
    "Allein Gott in der Höh' sei Ehr",
    "Ein' feste Burg ist unser Gott",
    "Ich bin ja, Herr, in deiner Macht",
    "Jesu, nun sei gepreiset",
    "Ach Gott, vom Himmel sieh' darein",
    "Weg, mein Herz, mit den Gedanken",
    "Was frag' ich nach der Welt",
    "Jesu, deine tiefen Wunden",
    "Nun aßt uns Gott, dem Herren",
    "Meine Augen schließ' ich jetzt",
    "Verleih' uns Frieden gnädiglich",
    "Es ist gewisslich an der Zeit",
    "Christ lag in Todesbanden",
    "Ach Gott, vom Himmel sieh' darein",
    "Jesu, meine Freude",
    "Jesu, meines Herzens Freud'",
    "das Was mein Gott will",
    "Herr Jesu Christ, du höchstes Gut",
    "Vater unser im Himmelreich",
    "Non lob', mein Seel', den Herren",
    "Jesu, der du meine Seele",
    "Befiehl du deine Wege",
    "Gib dich zufrieden und sei stille",
    "Ich dank' dir, lieber Herre",
    "Ein' feste Burg ist unser Gott",
    "O Ewigkeit, du Donnerwort",
    "O Welt, sieh hier dein Leben",
    "Lobt Gott, ihr Christen, allzugleich",
    "Herzlich lieb hab' ich dich, o Herr",
    "Wie schön leuchtet der Morgenstern",
    "Ach Gott und Herr",
    "Eins ist not! ach Herr, dies Eine",
    "Wo soll ich fliehen hin",
    "Freu' dich sehr, o meine Seele",
    "Jesu, meine Freude",
    "Herr Jesu Christ, wahr'r Mensch und Gott",
    "Wär' Gott nicht mit uns diese Zeit",
    "Befiehl du deine Wege",
    "Herr, ich habe mißgehandelt",
    "Gelobet seist du, Jesu Christ",
    "Nun ruhen alle Wälder",
    "Es ist das Heil uns kommen her",
    "Was frag' ich nach der Welt",
    "Nimm von uns, Herr, du treuer Gott",
    "Was Gott tut, das ist wohlgetan",
    "Herr Jesu Christ, du höchstes Gut",
    "Herr Jesu Christ, mein's Lebens nicht",
    "Nun lob', mein Seel', den Herren",
    "Jesu, der du meine Seele",
    "Weg, mein Herz, mit den Gedanken",
    "Meinen Jesum laß ich nicht",
    "Warum betrübst du dich, mein Herz",
    "Ach lieben Christen, seid getrost",
    "Hilf, Gott, daß mir's gelinge",
    "Herr Christ, der ein'ge Gott's sohn",
    "Auf meinen lieben Gott",
    "Wie schön leuchtet der Morgenstern",
    "O Mensch, bewein' dein' Sünde groß",
    "Christus, der uns selig macht",
    "Ach Gott, wie manches Herzeleid",
    "Ein Lämmlein geht und trägt die Schuld",
    "Mach's mit mir, Gott, nach deiner",
    "Dank sei Gott in der Höhe",
    "O Gott, du frommer Gott",
    "Allein Gott in der Höh sei Ehr",
    "Das alte Jahr vergangen ist",
    "O Gott, du frommer Gott",
    "Christus, der ist mein Leben",
    "Herr, wie du willst, so schick's mit mir",
    "Herr, wie du willst so schick's mit mir",
    "Sanctus, Sanctus Dominus Deus Sabaoth",
    "Gott sei uns gnädig und harmherzig",
    "Wir Christenleut'",
    "Wenn mein Stündlein vorhanden ist",
    "Wie schön leuchtet der Morgenstern",
    "Jesu, meine Freude",
    "Mit Fried' und Freud' ich fahr' dahin",
    "Allein Gott in der Höh' sei Ehr'",
    "Jesu, nun sei gepreiset",
    "Liebster Jesu, wir sind hier",
    "Sei Lob und Ehr' dem höchsten Gut",
    "Nun danker alle Gott",
    "Wo soll ich fliehen hin",
    "Von Gott will ich nicht lassen",
    "Es woll uns Gott genädig sein",
    "Für deinen Thron tret' ich hiermit",
    "Es ist das Heil uns kommen her",
    "Wo Gott der Herr nicht bei uns hält",
    "O Gott, du frommer Gott",
    "Jesus, meine Zuversicht",
    "Wer nur den lieben Gott lässt walten",
    "Befiehl du deine Wege",
    "Ich dank' dir, lieber Herre",
    "Lobt Gott, ihr Christen, allzugleich",
    "Nun lieget alles unter dir",
    "Vom Himmel hoch, da komm' ich her",
    "O Haupt voll Blut und Wunden",
    "Meines Lebens letzte Zeit",
    "Was Gott tut, das ist wohlgetan",
    "Meinen Jesum laß ich nicht",
    "Ich hab' in Gottes Herz und Sinn",
    "Jesu, meiner Seelen Wonne",
    "Wenn mein Stündlein vorhanden ist",
    "Es woll' uns Gott genädig sein",
    "Allein Gott in der Höh sei Ehr",
    "Sei Lob und Ehr den höchsten Gut",
    "Nun ruhen alle Wälder",
    "Jesu, meine Freude",
    "Warum sollt' ich mich denn grämen",
    "Meine Seel' erhebt den Herren",
    "Allein zu dir, Herr Jesu Christ",
    "Wir Christenleut'",
    "Ermuntre dich, mein schwacher Geist",
    "Es ist gewisslich an der Zeit",
    "O Welt, sieh hier dein Leben",
    "Von Gott will ich nicht lassen",
    "Jesu, meiner Sellen Wonne",
    "O Welt, sieh heir dein Leben",
    "Befiehl du deine Wege",
    "Hilf, Herr Jesu, laß gelingen",
    "Jesu, der du meine Seele",
    "Kommt her zu mir, spricht Gottes Sohn",
    "Christ lag in Todesbanden",
]


def levenshtein_distance(s, t):
    """
    Calculate Levenshtein distance for two strings.
    See `flexible_levenshtein_distance()` for tests and comparison.
    """
    m = len(s)
    n = len(t)
    d = [[0] * (n + 1) for i in range(m + 1)]

    for i in range(1, m + 1):
        d[i][0] = i

    for j in range(1, n + 1):
        d[0][j] = j

    for j in range(1, n + 1):
        for i in range(1, m + 1):
            if s[i - 1] == t[j - 1]:
                cost = 0
            else:
                cost = 1
            d[i][j] = min(d[i - 1][j] + 1,  # deletion
                          d[i][j - 1] + 1,  # insertion
                          d[i - 1][j - 1] + cost)  # substitution

    return d[m][n]


def flexible_levenshtein_distance(
        str1: str,
        str2: str,
        use_shorter_length: bool = True,
        case_matters: bool = False,
        ignore_characters: str = ".,:;'"
) -> int:
    """
    Compare two strings (here chorale titles) with the Levenshtein distances,
    but with flexibilty to certain known deviations.

    For example, the presence or absence of inverted commas:

    >>> w = "Ich hab' mein' Sach'"
    >>> without = "Ich hab mein Sach"
    >>> levenshtein_distance(w, without)
    3

    >>> flexible_levenshtein_distance(w, without, ignore_characters="'")
    0

    And in the comparison of shorter vs full titles as in the following:

    >>> full = "Ich hab mein Sach Gott heimgestellt"
    >>> levenshtein_distance(full, without)
    18

    >>> flexible_levenshtein_distance(full, without, use_shorter_length=True)
    0

    Also helps to omit verse numbers and other parenthetic ends,
    ... but only a bit if there are other divergences earlier on as in the following:

    >>> short = "Du Friedensfürst, Herr Jesu Christ"
    >>> long = "Du Friedefürst, Herr Jesu Christ (v. 1)"  # NB not "Friedens"

    >>> levenshtein_distance(short, long)  # 7 + 2
    9

    >>> flexible_levenshtein_distance(short, long, use_shorter_length=True)
    4

    :param str1: string 1 to compare with ...

    :param str2: string 2.

    :param use_shorter_length: bool. If True, take the shorter string length and only compare
    with that much of the longer string. Useful when you expect partial-vs-complete comparisons.
    first part of the N charac

    :param case_matters: bool. False by default. If True then ignore case differences ("a" = "A").

    :param ignore_characters: A string of all the characters to ignore, e.g., punctuation. Runs
    before case_matters as characters to ignore may be case-sensitive.

    :return: int

    """

    if str1 == str2:  # worth checking!
        return 0

    if ignore_characters:
        for c in ignore_characters:
            str1 = str1.replace(c, "")
            str2 = str2.replace(c, "")

    if use_shorter_length:
        min_len = min(len(str1), len(str2))
        str1 = str1[:min_len]
        str2 = str2[:min_len]

    if not case_matters:
        str1 = str1.lower()
        str2 = str2.lower()

    return levenshtein_distance(str1, str2)


def catalogue_convert(
        in_entry: str,
        in_cat: str = "Riemenschneider",
        out_cat: str = "text",
) -> str:
    """
    Convert from one catalogue reference to another.
    E.g., to get the text (name / title) from a Riemenschneider number:

    >>> catalogue_convert("1", in_cat="Riemenschneider", out_cat="text")
    'Aus meines Herzens Grunde'

    and vice versa:

    >>> catalogue_convert("Aus meines Herzens Grunde", in_cat="text", out_cat="Riemenschneider")
    '1'

    """

    in_col = col_dict[in_cat]  # raises error if not there
    out_col = col_dict[out_cat]  # "

    for row in catalogue:
        if row[in_col] == in_entry:
            return row[out_col]

    return ""



def compare_titles_with_catalogue(titles: List[str],
                                  in_cat="Riemenschneider",
                                  out_cat="tune",
                                  threshold=6
                                  ):

    errors = 0

    for i, title  in enumerate(titles, 1):
        if title is None:
            print(i, "None")
            continue
        catalogue_title = catalogue_convert(str(i), in_cat=in_cat, out_cat=out_cat)

        if catalogue_title is None:
            catalogue_title = ""

        d = flexible_levenshtein_distance(title, catalogue_title)

        if d > threshold:
            print(i, d, title, "///", catalogue_title)
            errors += 1
        else:
            print(i)

    print(errors)

    return errors




def compare_score_and_catalogue():
    """
    Compare a list of titles on the scores with those in the catalogue
    with the hypothesis that the catalogue is CPE.
    """
    global score_titles
    return compare_titles_with_catalogue(score_titles[1:],
                                         in_cat="CPE",
                                         threshold=3)


def compare_analysis_and_catalogue():
    """
    Compare a list of titles on the analyses with those in the catalogue
    with the hypothesis that the catalogue is Riemenschneider.
    """
    global score_titles
    return compare_titles_with_catalogue(score_titles[1:])

# ------------------------------------------------------------------------------

if __name__ == "__main__":
    import doctest
    doctest.testmod()
